package k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecDriverVolumeDevices
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecDriverVolumeDevices {

    private String devicePath;


    private String name;


    public V1beta2SparkApplicationSpecDriverVolumeDevices devicePath(String devicePath) {

        this.devicePath = devicePath;
        return this;
    }

    /**
     * Get devicePath
     *
     * @return devicePath
     **/
    @ApiModelProperty(required = true, value = "")

    public String getDevicePath() {
        return devicePath;
    }


    public void setDevicePath(String devicePath) {
        this.devicePath = devicePath;
    }


    public V1beta2SparkApplicationSpecDriverVolumeDevices name(String name) {

        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @ApiModelProperty(required = true, value = "")

    public String getName() {
        return name;
    }


    public void setName(String name) {
        this.name = name;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecDriverVolumeDevices v1beta2SparkApplicationSpecDriverVolumeDevices =
                (V1beta2SparkApplicationSpecDriverVolumeDevices) o;
        return Objects.equals(this.devicePath, v1beta2SparkApplicationSpecDriverVolumeDevices.devicePath) &&
                Objects.equals(this.name, v1beta2SparkApplicationSpecDriverVolumeDevices.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(devicePath, name);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecDriverVolumeDevices {\n");
        sb.append("    devicePath: ").append(toIndentedString(devicePath)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

