package k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecDriverSecrets
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecDriverSecrets {

    private String name;


    private String path;


    private String secretType;


    public V1beta2SparkApplicationSpecDriverSecrets name(String name) {

        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @ApiModelProperty(required = true, value = "")

    public String getName() {
        return name;
    }


    public void setName(String name) {
        this.name = name;
    }


    public V1beta2SparkApplicationSpecDriverSecrets path(String path) {

        this.path = path;
        return this;
    }

    /**
     * Get path
     *
     * @return path
     **/
    @ApiModelProperty(required = true, value = "")

    public String getPath() {
        return path;
    }


    public void setPath(String path) {
        this.path = path;
    }


    public V1beta2SparkApplicationSpecDriverSecrets secretType(String secretType) {

        this.secretType = secretType;
        return this;
    }

    /**
     * Get secretType
     *
     * @return secretType
     **/
    @ApiModelProperty(required = true, value = "")

    public String getSecretType() {
        return secretType;
    }


    public void setSecretType(String secretType) {
        this.secretType = secretType;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecDriverSecrets v1beta2SparkApplicationSpecDriverSecrets =
                (V1beta2SparkApplicationSpecDriverSecrets) o;
        return Objects.equals(this.name, v1beta2SparkApplicationSpecDriverSecrets.name) &&
                Objects.equals(this.path, v1beta2SparkApplicationSpecDriverSecrets.path) &&
                Objects.equals(this.secretType, v1beta2SparkApplicationSpecDriverSecrets.secretType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, path, secretType);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecDriverSecrets {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    path: ").append(toIndentedString(path)).append("\n");
        sb.append("    secretType: ").append(toIndentedString(secretType)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

