package k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution {

    private V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreference preference;


    private Integer weight;


    public V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution preference(V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreference preference) {

        this.preference = preference;
        return this;
    }

    /**
     * Get preference
     *
     * @return preference
     **/
    @ApiModelProperty(required = true, value = "")

    public V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreference getPreference() {
        return preference;
    }


    public void setPreference(V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreference preference) {
        this.preference = preference;
    }


    public V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution weight(Integer weight) {

        this.weight = weight;
        return this;
    }

    /**
     * Get weight
     *
     * @return weight
     **/
    @ApiModelProperty(required = true, value = "")

    public Integer getWeight() {
        return weight;
    }


    public void setWeight(Integer weight) {
        this.weight = weight;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution v1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution = (V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution) o;
        return Objects.equals(this.preference,
                v1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution.preference) &&
                Objects.equals(this.weight,
                        v1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution.weight);
    }

    @Override
    public int hashCode() {
        return Objects.hash(preference, weight);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class " +
                "V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution" +
                " {\n");
        sb.append("    preference: ").append(toIndentedString(preference)).append("\n");
        sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

