package k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecCsi
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecCsi {

    private String driver;


    private String fsType;


    private V1beta2SparkApplicationSpecCephfsSecretRef nodePublishSecretRef;


    private Boolean readOnly;


    private Map<String, String> volumeAttributes = null;


    public V1beta2SparkApplicationSpecCsi driver(String driver) {

        this.driver = driver;
        return this;
    }

    /**
     * Get driver
     *
     * @return driver
     **/
    @ApiModelProperty(required = true, value = "")

    public String getDriver() {
        return driver;
    }


    public void setDriver(String driver) {
        this.driver = driver;
    }


    public V1beta2SparkApplicationSpecCsi fsType(String fsType) {

        this.fsType = fsType;
        return this;
    }

    /**
     * Get fsType
     *
     * @return fsType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getFsType() {
        return fsType;
    }


    public void setFsType(String fsType) {
        this.fsType = fsType;
    }


    public V1beta2SparkApplicationSpecCsi nodePublishSecretRef(V1beta2SparkApplicationSpecCephfsSecretRef nodePublishSecretRef) {

        this.nodePublishSecretRef = nodePublishSecretRef;
        return this;
    }

    /**
     * Get nodePublishSecretRef
     *
     * @return nodePublishSecretRef
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1beta2SparkApplicationSpecCephfsSecretRef getNodePublishSecretRef() {
        return nodePublishSecretRef;
    }


    public void setNodePublishSecretRef(V1beta2SparkApplicationSpecCephfsSecretRef nodePublishSecretRef) {
        this.nodePublishSecretRef = nodePublishSecretRef;
    }


    public V1beta2SparkApplicationSpecCsi readOnly(Boolean readOnly) {

        this.readOnly = readOnly;
        return this;
    }

    /**
     * Get readOnly
     *
     * @return readOnly
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getReadOnly() {
        return readOnly;
    }


    public void setReadOnly(Boolean readOnly) {
        this.readOnly = readOnly;
    }


    public V1beta2SparkApplicationSpecCsi volumeAttributes(Map<String, String> volumeAttributes) {

        this.volumeAttributes = volumeAttributes;
        return this;
    }

    public V1beta2SparkApplicationSpecCsi putVolumeAttributesItem(String key, String volumeAttributesItem) {
        if (this.volumeAttributes == null) {
            this.volumeAttributes = new HashMap<>();
        }
        this.volumeAttributes.put(key, volumeAttributesItem);
        return this;
    }

    /**
     * Get volumeAttributes
     *
     * @return volumeAttributes
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Map<String, String> getVolumeAttributes() {
        return volumeAttributes;
    }


    public void setVolumeAttributes(Map<String, String> volumeAttributes) {
        this.volumeAttributes = volumeAttributes;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecCsi v1beta2SparkApplicationSpecCsi = (V1beta2SparkApplicationSpecCsi) o;
        return Objects.equals(this.driver, v1beta2SparkApplicationSpecCsi.driver) &&
                Objects.equals(this.fsType, v1beta2SparkApplicationSpecCsi.fsType) &&
                Objects.equals(this.nodePublishSecretRef, v1beta2SparkApplicationSpecCsi.nodePublishSecretRef) &&
                Objects.equals(this.readOnly, v1beta2SparkApplicationSpecCsi.readOnly) &&
                Objects.equals(this.volumeAttributes, v1beta2SparkApplicationSpecCsi.volumeAttributes);
    }

    @Override
    public int hashCode() {
        return Objects.hash(driver, fsType, nodePublishSecretRef, readOnly, volumeAttributes);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecCsi {\n");
        sb.append("    driver: ").append(toIndentedString(driver)).append("\n");
        sb.append("    fsType: ").append(toIndentedString(fsType)).append("\n");
        sb.append("    nodePublishSecretRef: ").append(toIndentedString(nodePublishSecretRef)).append("\n");
        sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
        sb.append("    volumeAttributes: ").append(toIndentedString(volumeAttributes)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

