/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package k8s.flinkoperator;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta1FlinkClusterSpecTaskManagerPorts
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-02-19T16:59" +
        ":54.980Z[Etc/UTC]")
public class V1beta1FlinkClusterSpecTaskManagerPorts {
    @JsonProperty("data")
    private Integer data;

    @JsonProperty("query")
    private Integer query;

    @JsonProperty("rpc")
    private Integer rpc;


    public V1beta1FlinkClusterSpecTaskManagerPorts data(Integer data) {

        this.data = data;
        return this;
    }

    /**
     * Get data
     *
     * @return data
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getData() {
        return data;
    }


    public void setData(Integer data) {
        this.data = data;
    }


    public V1beta1FlinkClusterSpecTaskManagerPorts query(Integer query) {

        this.query = query;
        return this;
    }

    /**
     * Get query
     *
     * @return query
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getQuery() {
        return query;
    }


    public void setQuery(Integer query) {
        this.query = query;
    }


    public V1beta1FlinkClusterSpecTaskManagerPorts rpc(Integer rpc) {

        this.rpc = rpc;
        return this;
    }

    /**
     * Get rpc
     *
     * @return rpc
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getRpc() {
        return rpc;
    }


    public void setRpc(Integer rpc) {
        this.rpc = rpc;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta1FlinkClusterSpecTaskManagerPorts v1beta1FlinkClusterSpecTaskManagerPorts =
                (V1beta1FlinkClusterSpecTaskManagerPorts) o;
        return Objects.equals(this.data, v1beta1FlinkClusterSpecTaskManagerPorts.data) &&
                Objects.equals(this.query, v1beta1FlinkClusterSpecTaskManagerPorts.query) &&
                Objects.equals(this.rpc, v1beta1FlinkClusterSpecTaskManagerPorts.rpc);
    }

    @Override
    public int hashCode() {
        return Objects.hash(data, query, rpc);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta1FlinkClusterSpecTaskManagerPorts {\n");
        sb.append("    data: ").append(toIndentedString(data)).append("\n");
        sb.append("    query: ").append(toIndentedString(query)).append("\n");
        sb.append("    rpc: ").append(toIndentedString(rpc)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

