/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package k8s.flinkoperator;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * V1beta1FlinkClusterStatusControl
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-02-19T16:59" +
        ":54.980Z[Etc/UTC]")
public class V1beta1FlinkClusterStatusControl {
    @JsonProperty("details")
    private Map<String, String> details = null;

    @JsonProperty("message")
    private String message;

    @JsonProperty("name")
    private String name;

    @JsonProperty("state")
    private String state;

    @JsonProperty("updateTime")
    private String updateTime;


    public V1beta1FlinkClusterStatusControl details(Map<String, String> details) {

        this.details = details;
        return this;
    }

    public V1beta1FlinkClusterStatusControl putDetailsItem(String key, String detailsItem) {
        if (this.details == null) {
            this.details = new HashMap<>();
        }
        this.details.put(key, detailsItem);
        return this;
    }

    /**
     * Get details
     *
     * @return details
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Map<String, String> getDetails() {
        return details;
    }


    public void setDetails(Map<String, String> details) {
        this.details = details;
    }


    public V1beta1FlinkClusterStatusControl message(String message) {

        this.message = message;
        return this;
    }

    /**
     * Get message
     *
     * @return message
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getMessage() {
        return message;
    }


    public void setMessage(String message) {
        this.message = message;
    }


    public V1beta1FlinkClusterStatusControl name(String name) {

        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @ApiModelProperty(required = true, value = "")

    public String getName() {
        return name;
    }


    public void setName(String name) {
        this.name = name;
    }


    public V1beta1FlinkClusterStatusControl state(String state) {

        this.state = state;
        return this;
    }

    /**
     * Get state
     *
     * @return state
     **/
    @ApiModelProperty(required = true, value = "")

    public String getState() {
        return state;
    }


    public void setState(String state) {
        this.state = state;
    }


    public V1beta1FlinkClusterStatusControl updateTime(String updateTime) {

        this.updateTime = updateTime;
        return this;
    }

    /**
     * Get updateTime
     *
     * @return updateTime
     **/
    @ApiModelProperty(required = true, value = "")

    public String getUpdateTime() {
        return updateTime;
    }


    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta1FlinkClusterStatusControl v1beta1FlinkClusterStatusControl = (V1beta1FlinkClusterStatusControl) o;
        return Objects.equals(this.details, v1beta1FlinkClusterStatusControl.details) &&
                Objects.equals(this.message, v1beta1FlinkClusterStatusControl.message) &&
                Objects.equals(this.name, v1beta1FlinkClusterStatusControl.name) &&
                Objects.equals(this.state, v1beta1FlinkClusterStatusControl.state) &&
                Objects.equals(this.updateTime, v1beta1FlinkClusterStatusControl.updateTime);
    }

    @Override
    public int hashCode() {
        return Objects.hash(details, message, name, state, updateTime);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta1FlinkClusterStatusControl {\n");
        sb.append("    details: ").append(toIndentedString(details)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    state: ").append(toIndentedString(state)).append("\n");
        sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

