### Service
apiVersion: v1
kind: Service
metadata:
  name: extender-service
spec:
  selector:
    app: testbed-operator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http