### Service
apiVersion: v1
kind: Service
metadata:
  name: external-scheduling-interface-service
spec:
  selector:
    app: scheduling-operator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
      name: http