{{- if .Values.scheduler.create}}
  {{- if .Values.scheduler.serviceaccount.create}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.scheduler.serviceaccount.name|quote}}
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-scheduler-cluster-admin
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: {{ .Values.scheduler.serviceaccount.name | quote}}
    {{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-scheduler-config
  namespace: kube-system
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta2
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: external-scheduler
    extenders:
      - urlPrefix: "http://10.112.2.4:80"
        filterVerb: "extender/filter"
        preemptVerb: "extender/preemption"
        weight: 1
        enableHTTPS: false
        nodeCacheCapable: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-scheduler
  namespace: kube-system
  labels:
    app: external-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-scheduler
  template:
    metadata:
      labels:
        app: external-scheduler
    spec:
      serviceAccountName: {{.Values.scheduler.serviceaccount.name|quote}}
      volumes:
        - name: external-scheduler-config
          configMap:
            name: external-scheduler-config
      containers:
        - name: external-scheduler-ctr
          image: {{.Values.image.repository}}test-kube-scheduler
          imagePullPolicy: Always
          args:
            - kube-scheduler
            - --config=/external-scheduler/config.yaml
            - -v=4
          volumeMounts:
            - name: external-scheduler-config
              mountPath: /external-scheduler

{{- end}}