/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package k8s.flinkoperator;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * V1beta1FlinkClusterStatusComponentsJob
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-02-19T16:59" +
        ":54.980Z[Etc/UTC]")
public class V1beta1FlinkClusterStatusComponentsJob {
    @JsonProperty("completionTime")
    private OffsetDateTime completionTime;

    @JsonProperty("deployTime")
    private String deployTime;

    @JsonProperty("failureReasons")
    private List<String> failureReasons = null;

    @JsonProperty("finalSavepoint")
    private Boolean finalSavepoint;

    @JsonProperty("fromSavepoint")
    private String fromSavepoint;

    @JsonProperty("id")
    private String id;

    @JsonProperty("name")
    private String name;

    @JsonProperty("restartCount")
    private Integer restartCount;

    @JsonProperty("savepointGeneration")
    private Integer savepointGeneration;

    @JsonProperty("savepointLocation")
    private String savepointLocation;

    @JsonProperty("savepointTime")
    private String savepointTime;

    @JsonProperty("startTime")
    private String startTime;

    @JsonProperty("state")
    private String state;

    @JsonProperty("submitterName")
    private String submitterName;


    public V1beta1FlinkClusterStatusComponentsJob completionTime(OffsetDateTime completionTime) {

        this.completionTime = completionTime;
        return this;
    }

    /**
     * Get completionTime
     *
     * @return completionTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public OffsetDateTime getCompletionTime() {
        return completionTime;
    }


    public void setCompletionTime(OffsetDateTime completionTime) {
        this.completionTime = completionTime;
    }


    public V1beta1FlinkClusterStatusComponentsJob deployTime(String deployTime) {

        this.deployTime = deployTime;
        return this;
    }

    /**
     * Get deployTime
     *
     * @return deployTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getDeployTime() {
        return deployTime;
    }


    public void setDeployTime(String deployTime) {
        this.deployTime = deployTime;
    }


    public V1beta1FlinkClusterStatusComponentsJob failureReasons(List<String> failureReasons) {

        this.failureReasons = failureReasons;
        return this;
    }

    public V1beta1FlinkClusterStatusComponentsJob addFailureReasonsItem(String failureReasonsItem) {
        if (this.failureReasons == null) {
            this.failureReasons = new ArrayList<>();
        }
        this.failureReasons.add(failureReasonsItem);
        return this;
    }

    /**
     * Get failureReasons
     *
     * @return failureReasons
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<String> getFailureReasons() {
        return failureReasons;
    }


    public void setFailureReasons(List<String> failureReasons) {
        this.failureReasons = failureReasons;
    }


    public V1beta1FlinkClusterStatusComponentsJob finalSavepoint(Boolean finalSavepoint) {

        this.finalSavepoint = finalSavepoint;
        return this;
    }

    /**
     * Get finalSavepoint
     *
     * @return finalSavepoint
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getFinalSavepoint() {
        return finalSavepoint;
    }


    public void setFinalSavepoint(Boolean finalSavepoint) {
        this.finalSavepoint = finalSavepoint;
    }


    public V1beta1FlinkClusterStatusComponentsJob fromSavepoint(String fromSavepoint) {

        this.fromSavepoint = fromSavepoint;
        return this;
    }

    /**
     * Get fromSavepoint
     *
     * @return fromSavepoint
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getFromSavepoint() {
        return fromSavepoint;
    }


    public void setFromSavepoint(String fromSavepoint) {
        this.fromSavepoint = fromSavepoint;
    }


    public V1beta1FlinkClusterStatusComponentsJob id(String id) {

        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getId() {
        return id;
    }


    public void setId(String id) {
        this.id = id;
    }


    public V1beta1FlinkClusterStatusComponentsJob name(String name) {

        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getName() {
        return name;
    }


    public void setName(String name) {
        this.name = name;
    }


    public V1beta1FlinkClusterStatusComponentsJob restartCount(Integer restartCount) {

        this.restartCount = restartCount;
        return this;
    }

    /**
     * Get restartCount
     *
     * @return restartCount
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getRestartCount() {
        return restartCount;
    }


    public void setRestartCount(Integer restartCount) {
        this.restartCount = restartCount;
    }


    public V1beta1FlinkClusterStatusComponentsJob savepointGeneration(Integer savepointGeneration) {

        this.savepointGeneration = savepointGeneration;
        return this;
    }

    /**
     * Get savepointGeneration
     *
     * @return savepointGeneration
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getSavepointGeneration() {
        return savepointGeneration;
    }


    public void setSavepointGeneration(Integer savepointGeneration) {
        this.savepointGeneration = savepointGeneration;
    }


    public V1beta1FlinkClusterStatusComponentsJob savepointLocation(String savepointLocation) {

        this.savepointLocation = savepointLocation;
        return this;
    }

    /**
     * Get savepointLocation
     *
     * @return savepointLocation
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getSavepointLocation() {
        return savepointLocation;
    }


    public void setSavepointLocation(String savepointLocation) {
        this.savepointLocation = savepointLocation;
    }


    public V1beta1FlinkClusterStatusComponentsJob savepointTime(String savepointTime) {

        this.savepointTime = savepointTime;
        return this;
    }

    /**
     * Get savepointTime
     *
     * @return savepointTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getSavepointTime() {
        return savepointTime;
    }


    public void setSavepointTime(String savepointTime) {
        this.savepointTime = savepointTime;
    }


    public V1beta1FlinkClusterStatusComponentsJob startTime(String startTime) {

        this.startTime = startTime;
        return this;
    }

    /**
     * Get startTime
     *
     * @return startTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getStartTime() {
        return startTime;
    }


    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }


    public V1beta1FlinkClusterStatusComponentsJob state(String state) {

        this.state = state;
        return this;
    }

    /**
     * Get state
     *
     * @return state
     **/
    @ApiModelProperty(required = true, value = "")

    public String getState() {
        return state;
    }


    public void setState(String state) {
        this.state = state;
    }


    public V1beta1FlinkClusterStatusComponentsJob submitterName(String submitterName) {

        this.submitterName = submitterName;
        return this;
    }

    /**
     * Get submitterName
     *
     * @return submitterName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getSubmitterName() {
        return submitterName;
    }


    public void setSubmitterName(String submitterName) {
        this.submitterName = submitterName;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta1FlinkClusterStatusComponentsJob v1beta1FlinkClusterStatusComponentsJob =
                (V1beta1FlinkClusterStatusComponentsJob) o;
        return Objects.equals(this.completionTime, v1beta1FlinkClusterStatusComponentsJob.completionTime) &&
                Objects.equals(this.deployTime, v1beta1FlinkClusterStatusComponentsJob.deployTime) &&
                Objects.equals(this.failureReasons, v1beta1FlinkClusterStatusComponentsJob.failureReasons) &&
                Objects.equals(this.finalSavepoint, v1beta1FlinkClusterStatusComponentsJob.finalSavepoint) &&
                Objects.equals(this.fromSavepoint, v1beta1FlinkClusterStatusComponentsJob.fromSavepoint) &&
                Objects.equals(this.id, v1beta1FlinkClusterStatusComponentsJob.id) &&
                Objects.equals(this.name, v1beta1FlinkClusterStatusComponentsJob.name) &&
                Objects.equals(this.restartCount, v1beta1FlinkClusterStatusComponentsJob.restartCount) &&
                Objects.equals(this.savepointGeneration, v1beta1FlinkClusterStatusComponentsJob.savepointGeneration) &&
                Objects.equals(this.savepointLocation, v1beta1FlinkClusterStatusComponentsJob.savepointLocation) &&
                Objects.equals(this.savepointTime, v1beta1FlinkClusterStatusComponentsJob.savepointTime) &&
                Objects.equals(this.startTime, v1beta1FlinkClusterStatusComponentsJob.startTime) &&
                Objects.equals(this.state, v1beta1FlinkClusterStatusComponentsJob.state) &&
                Objects.equals(this.submitterName, v1beta1FlinkClusterStatusComponentsJob.submitterName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(completionTime, deployTime, failureReasons, finalSavepoint, fromSavepoint, id, name,
                restartCount, savepointGeneration, savepointLocation, savepointTime, startTime, state, submitterName);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta1FlinkClusterStatusComponentsJob {\n");
        sb.append("    completionTime: ").append(toIndentedString(completionTime)).append("\n");
        sb.append("    deployTime: ").append(toIndentedString(deployTime)).append("\n");
        sb.append("    failureReasons: ").append(toIndentedString(failureReasons)).append("\n");
        sb.append("    finalSavepoint: ").append(toIndentedString(finalSavepoint)).append("\n");
        sb.append("    fromSavepoint: ").append(toIndentedString(fromSavepoint)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    restartCount: ").append(toIndentedString(restartCount)).append("\n");
        sb.append("    savepointGeneration: ").append(toIndentedString(savepointGeneration)).append("\n");
        sb.append("    savepointLocation: ").append(toIndentedString(savepointLocation)).append("\n");
        sb.append("    savepointTime: ").append(toIndentedString(savepointTime)).append("\n");
        sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
        sb.append("    state: ").append(toIndentedString(state)).append("\n");
        sb.append("    submitterName: ").append(toIndentedString(submitterName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

