/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package k8s.flinkoperator;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta1FlinkClusterStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-02-19T16:59" +
        ":54.980Z[Etc/UTC]")
public class V1beta1FlinkClusterStatus {
    @JsonProperty("components")
    private V1beta1FlinkClusterStatusComponents components;

    @JsonProperty("control")
    private V1beta1FlinkClusterStatusControl control;

    @JsonProperty("lastUpdateTime")
    private String lastUpdateTime;

    @JsonProperty("revision")
    private V1beta1FlinkClusterStatusRevision revision;

    @JsonProperty("savepoint")
    private V1beta1FlinkClusterStatusSavepoint savepoint;

    @JsonProperty("state")
    private String state;


    public V1beta1FlinkClusterStatus components(V1beta1FlinkClusterStatusComponents components) {

        this.components = components;
        return this;
    }

    /**
     * Get components
     *
     * @return components
     **/
    @ApiModelProperty(required = true, value = "")

    public V1beta1FlinkClusterStatusComponents getComponents() {
        return components;
    }


    public void setComponents(V1beta1FlinkClusterStatusComponents components) {
        this.components = components;
    }


    public V1beta1FlinkClusterStatus control(V1beta1FlinkClusterStatusControl control) {

        this.control = control;
        return this;
    }

    /**
     * Get control
     *
     * @return control
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1beta1FlinkClusterStatusControl getControl() {
        return control;
    }


    public void setControl(V1beta1FlinkClusterStatusControl control) {
        this.control = control;
    }


    public V1beta1FlinkClusterStatus lastUpdateTime(String lastUpdateTime) {

        this.lastUpdateTime = lastUpdateTime;
        return this;
    }

    /**
     * Get lastUpdateTime
     *
     * @return lastUpdateTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getLastUpdateTime() {
        return lastUpdateTime;
    }


    public void setLastUpdateTime(String lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }


    public V1beta1FlinkClusterStatus revision(V1beta1FlinkClusterStatusRevision revision) {

        this.revision = revision;
        return this;
    }

    /**
     * Get revision
     *
     * @return revision
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1beta1FlinkClusterStatusRevision getRevision() {
        return revision;
    }


    public void setRevision(V1beta1FlinkClusterStatusRevision revision) {
        this.revision = revision;
    }


    public V1beta1FlinkClusterStatus savepoint(V1beta1FlinkClusterStatusSavepoint savepoint) {

        this.savepoint = savepoint;
        return this;
    }

    /**
     * Get savepoint
     *
     * @return savepoint
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1beta1FlinkClusterStatusSavepoint getSavepoint() {
        return savepoint;
    }


    public void setSavepoint(V1beta1FlinkClusterStatusSavepoint savepoint) {
        this.savepoint = savepoint;
    }


    public V1beta1FlinkClusterStatus state(String state) {

        this.state = state;
        return this;
    }

    /**
     * Get state
     *
     * @return state
     **/
    @ApiModelProperty(required = true, value = "")

    public String getState() {
        return state;
    }


    public void setState(String state) {
        this.state = state;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta1FlinkClusterStatus v1beta1FlinkClusterStatus = (V1beta1FlinkClusterStatus) o;
        return Objects.equals(this.components, v1beta1FlinkClusterStatus.components) &&
                Objects.equals(this.control, v1beta1FlinkClusterStatus.control) &&
                Objects.equals(this.lastUpdateTime, v1beta1FlinkClusterStatus.lastUpdateTime) &&
                Objects.equals(this.revision, v1beta1FlinkClusterStatus.revision) &&
                Objects.equals(this.savepoint, v1beta1FlinkClusterStatus.savepoint) &&
                Objects.equals(this.state, v1beta1FlinkClusterStatus.state);
    }

    @Override
    public int hashCode() {
        return Objects.hash(components, control, lastUpdateTime, revision, savepoint, state);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta1FlinkClusterStatus {\n");
        sb.append("    components: ").append(toIndentedString(components)).append("\n");
        sb.append("    control: ").append(toIndentedString(control)).append("\n");
        sb.append("    lastUpdateTime: ").append(toIndentedString(lastUpdateTime)).append("\n");
        sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
        sb.append("    savepoint: ").append(toIndentedString(savepoint)).append("\n");
        sb.append("    state: ").append(toIndentedString(state)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

