apiVersion: esi.tu-berlin.de/v1alpha1
kind: BatchJob
metadata:
  name: batchjob-flink2
  namespace: default
spec:
  externalScheduler:
    profiler:
      - batchjob-flink: 24 (16)
        batchjob-flink3: 25 (16)
        batchjob-sample: 27 (16)
        batchjob-sample3: 31 (8)
        spark-crawler: 30 (7)
  flinkSpec:
    args:
      - --input
      - ./README.txt
    className: org.apache.flink.streaming.examples.wordcount.WordCount
    jarFile: ./examples/streaming/WordCount.jar