package k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecDriverValueFromResourceFieldRef
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecDriverValueFromResourceFieldRef {

    private String containerName;


    private Object divisor;


    private String resource;


    public V1beta2SparkApplicationSpecDriverValueFromResourceFieldRef containerName(String containerName) {

        this.containerName = containerName;
        return this;
    }

    /**
     * Get containerName
     *
     * @return containerName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getContainerName() {
        return containerName;
    }


    public void setContainerName(String containerName) {
        this.containerName = containerName;
    }


    public V1beta2SparkApplicationSpecDriverValueFromResourceFieldRef divisor(Object divisor) {

        this.divisor = divisor;
        return this;
    }

    /**
     * Get divisor
     *
     * @return divisor
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Object getDivisor() {
        return divisor;
    }


    public void setDivisor(Object divisor) {
        this.divisor = divisor;
    }


    public V1beta2SparkApplicationSpecDriverValueFromResourceFieldRef resource(String resource) {

        this.resource = resource;
        return this;
    }

    /**
     * Get resource
     *
     * @return resource
     **/
    @ApiModelProperty(required = true, value = "")

    public String getResource() {
        return resource;
    }


    public void setResource(String resource) {
        this.resource = resource;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecDriverValueFromResourceFieldRef v1beta2SparkApplicationSpecDriverValueFromResourceFieldRef = (V1beta2SparkApplicationSpecDriverValueFromResourceFieldRef) o;
        return Objects.equals(this.containerName,
                v1beta2SparkApplicationSpecDriverValueFromResourceFieldRef.containerName) &&
                Objects.equals(this.divisor, v1beta2SparkApplicationSpecDriverValueFromResourceFieldRef.divisor) &&
                Objects.equals(this.resource, v1beta2SparkApplicationSpecDriverValueFromResourceFieldRef.resource);
    }

    @Override
    public int hashCode() {
        return Objects.hash(containerName, divisor, resource);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecDriverValueFromResourceFieldRef {\n");
        sb.append("    containerName: ").append(toIndentedString(containerName)).append("\n");
        sb.append("    divisor: ").append(toIndentedString(divisor)).append("\n");
        sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

