package k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecDriverHostAliases
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecDriverHostAliases {

    private List<String> hostnames = null;


    private String ip;


    public V1beta2SparkApplicationSpecDriverHostAliases hostnames(List<String> hostnames) {

        this.hostnames = hostnames;
        return this;
    }

    public V1beta2SparkApplicationSpecDriverHostAliases addHostnamesItem(String hostnamesItem) {
        if (this.hostnames == null) {
            this.hostnames = new ArrayList<>();
        }
        this.hostnames.add(hostnamesItem);
        return this;
    }

    /**
     * Get hostnames
     *
     * @return hostnames
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<String> getHostnames() {
        return hostnames;
    }


    public void setHostnames(List<String> hostnames) {
        this.hostnames = hostnames;
    }


    public V1beta2SparkApplicationSpecDriverHostAliases ip(String ip) {

        this.ip = ip;
        return this;
    }

    /**
     * Get ip
     *
     * @return ip
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getIp() {
        return ip;
    }


    public void setIp(String ip) {
        this.ip = ip;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecDriverHostAliases v1beta2SparkApplicationSpecDriverHostAliases =
                (V1beta2SparkApplicationSpecDriverHostAliases) o;
        return Objects.equals(this.hostnames, v1beta2SparkApplicationSpecDriverHostAliases.hostnames) &&
                Objects.equals(this.ip, v1beta2SparkApplicationSpecDriverHostAliases.ip);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hostnames, ip);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecDriverHostAliases {\n");
        sb.append("    hostnames: ").append(toIndentedString(hostnames)).append("\n");
        sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

