apiVersion: esi.tu-berlin.de/v1alpha1
kind: Testbed
metadata:
  name: batchjob-slots
  namespace: test-namespace
spec:
  slotsPerNode: 4
  nodeLabel: "tuberlin.de/node-with-slots"
  resourcesPerSlot:
    cpu: "200m"
    memory: "896Mi"

---
apiVersion: esi.tu-berlin.de/v1alpha1
kind: Testbed
metadata:
  name: profiler-slots
  namespace: test-namespace
spec:
  slotsPerNode: 2
  nodeLabel: "tuberlin.de/node-with-slots-profiler"
  resourcesPerSlot:
    cpu: "200m"
    memory: "896Mi"