/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.k8s.flinkoperator;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * V1beta1FlinkClusterSpecJobManagerStatusConditions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-02-19T16:59" +
        ":54.980Z[Etc/UTC]")
public class V1beta1FlinkClusterSpecJobManagerStatusConditions {
    @JsonProperty("lastProbeTime")
    private OffsetDateTime lastProbeTime;

    @JsonProperty("lastTransitionTime")
    private OffsetDateTime lastTransitionTime;

    @JsonProperty("message")
    private String message;

    @JsonProperty("reason")
    private String reason;

    @JsonProperty("status")
    private String status;

    @JsonProperty("type")
    private String type;


    public V1beta1FlinkClusterSpecJobManagerStatusConditions lastProbeTime(OffsetDateTime lastProbeTime) {

        this.lastProbeTime = lastProbeTime;
        return this;
    }

    /**
     * Get lastProbeTime
     *
     * @return lastProbeTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public OffsetDateTime getLastProbeTime() {
        return lastProbeTime;
    }


    public void setLastProbeTime(OffsetDateTime lastProbeTime) {
        this.lastProbeTime = lastProbeTime;
    }


    public V1beta1FlinkClusterSpecJobManagerStatusConditions lastTransitionTime(OffsetDateTime lastTransitionTime) {

        this.lastTransitionTime = lastTransitionTime;
        return this;
    }

    /**
     * Get lastTransitionTime
     *
     * @return lastTransitionTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public OffsetDateTime getLastTransitionTime() {
        return lastTransitionTime;
    }


    public void setLastTransitionTime(OffsetDateTime lastTransitionTime) {
        this.lastTransitionTime = lastTransitionTime;
    }


    public V1beta1FlinkClusterSpecJobManagerStatusConditions message(String message) {

        this.message = message;
        return this;
    }

    /**
     * Get message
     *
     * @return message
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getMessage() {
        return message;
    }


    public void setMessage(String message) {
        this.message = message;
    }


    public V1beta1FlinkClusterSpecJobManagerStatusConditions reason(String reason) {

        this.reason = reason;
        return this;
    }

    /**
     * Get reason
     *
     * @return reason
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getReason() {
        return reason;
    }


    public void setReason(String reason) {
        this.reason = reason;
    }


    public V1beta1FlinkClusterSpecJobManagerStatusConditions status(String status) {

        this.status = status;
        return this;
    }

    /**
     * Get status
     *
     * @return status
     **/
    @ApiModelProperty(required = true, value = "")

    public String getStatus() {
        return status;
    }


    public void setStatus(String status) {
        this.status = status;
    }


    public V1beta1FlinkClusterSpecJobManagerStatusConditions type(String type) {

        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     **/
    @ApiModelProperty(required = true, value = "")

    public String getType() {
        return type;
    }


    public void setType(String type) {
        this.type = type;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta1FlinkClusterSpecJobManagerStatusConditions v1beta1FlinkClusterSpecJobManagerStatusConditions =
                (V1beta1FlinkClusterSpecJobManagerStatusConditions) o;
        return Objects.equals(this.lastProbeTime, v1beta1FlinkClusterSpecJobManagerStatusConditions.lastProbeTime) &&
                Objects.equals(this.lastTransitionTime,
                        v1beta1FlinkClusterSpecJobManagerStatusConditions.lastTransitionTime) &&
                Objects.equals(this.message, v1beta1FlinkClusterSpecJobManagerStatusConditions.message) &&
                Objects.equals(this.reason, v1beta1FlinkClusterSpecJobManagerStatusConditions.reason) &&
                Objects.equals(this.status, v1beta1FlinkClusterSpecJobManagerStatusConditions.status) &&
                Objects.equals(this.type, v1beta1FlinkClusterSpecJobManagerStatusConditions.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(lastProbeTime, lastTransitionTime, message, reason, status, type);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta1FlinkClusterSpecJobManagerStatusConditions {\n");
        sb.append("    lastProbeTime: ").append(toIndentedString(lastProbeTime)).append("\n");
        sb.append("    lastTransitionTime: ").append(toIndentedString(lastTransitionTime)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

