/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.k8s.flinkoperator;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta1FlinkClusterSpecBatchScheduler
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-02-19T16:59" +
        ":54.980Z[Etc/UTC]")
public class V1beta1FlinkClusterSpecBatchScheduler {
    @JsonProperty("name")
    private String name;

    @JsonProperty("priorityClassName")
    private String priorityClassName;

    @JsonProperty("queue")
    private String queue;


    public V1beta1FlinkClusterSpecBatchScheduler name(String name) {

        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @ApiModelProperty(required = true, value = "")

    public String getName() {
        return name;
    }


    public void setName(String name) {
        this.name = name;
    }


    public V1beta1FlinkClusterSpecBatchScheduler priorityClassName(String priorityClassName) {

        this.priorityClassName = priorityClassName;
        return this;
    }

    /**
     * Get priorityClassName
     *
     * @return priorityClassName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getPriorityClassName() {
        return priorityClassName;
    }


    public void setPriorityClassName(String priorityClassName) {
        this.priorityClassName = priorityClassName;
    }


    public V1beta1FlinkClusterSpecBatchScheduler queue(String queue) {

        this.queue = queue;
        return this;
    }

    /**
     * Get queue
     *
     * @return queue
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getQueue() {
        return queue;
    }


    public void setQueue(String queue) {
        this.queue = queue;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta1FlinkClusterSpecBatchScheduler v1beta1FlinkClusterSpecBatchScheduler =
                (V1beta1FlinkClusterSpecBatchScheduler) o;
        return Objects.equals(this.name, v1beta1FlinkClusterSpecBatchScheduler.name) &&
                Objects.equals(this.priorityClassName, v1beta1FlinkClusterSpecBatchScheduler.priorityClassName) &&
                Objects.equals(this.queue, v1beta1FlinkClusterSpecBatchScheduler.queue);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, priorityClassName, queue);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta1FlinkClusterSpecBatchScheduler {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    priorityClassName: ").append(toIndentedString(priorityClassName)).append("\n");
        sb.append("    queue: ").append(toIndentedString(queue)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

