/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.k8s.flinkoperator;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.fabric8.kubernetes.api.model.Container;
import io.fabric8.kubernetes.api.model.PodSecurityContext;
import io.fabric8.kubernetes.api.model.ResourceRequirements;
import io.fabric8.kubernetes.api.model.Toleration;
import io.fabric8.kubernetes.api.model.Volume;
import io.fabric8.kubernetes.api.model.VolumeMount;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * V1beta1FlinkClusterSpecJob
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-02-19T16:59" +
        ":54.980Z[Etc/UTC]")
public class V1beta1FlinkClusterSpecJob {
    @JsonProperty("allowNonRestoredState")
    private Boolean allowNonRestoredState;

    @JsonProperty("args")
    private List<String> args = null;

    @JsonProperty("autoSavepointSeconds")
    private Integer autoSavepointSeconds;

    @JsonProperty("cancelRequested")
    private Boolean cancelRequested;

    @JsonProperty("className")
    private String className;

    @JsonProperty("cleanupPolicy")
    private V1beta1FlinkClusterSpecJobCleanupPolicy cleanupPolicy;

    @JsonProperty("fromSavepoint")
    private String fromSavepoint;

    @JsonProperty("initContainers")
    private List<Container> initContainers = null;

    @JsonProperty("jarFile")
    private String jarFile;

    @JsonProperty("maxStateAgeToRestoreSeconds")
    private Integer maxStateAgeToRestoreSeconds;

    @JsonProperty("mode")
    private String mode;

    @JsonProperty("noLoggingToStdout")
    private Boolean noLoggingToStdout;

    @JsonProperty("nodeSelector")
    private Map<String, String> nodeSelector = null;

    @JsonProperty("parallelism")
    private Integer parallelism;

    @JsonProperty("podAnnotations")
    private Map<String, String> podAnnotations = null;

    @JsonProperty("podLabels")
    private Map<String, String> podLabels = null;

    @JsonProperty("pyFile")
    private String pyFile;

    @JsonProperty("pyFiles")
    private String pyFiles;

    @JsonProperty("pyModule")
    private String pyModule;

    @JsonProperty("resources")
    private ResourceRequirements resources;

    @JsonProperty("restartPolicy")
    private String restartPolicy;

    @JsonProperty("savepointGeneration")
    private Integer savepointGeneration;

    @JsonProperty("savepointsDir")
    private String savepointsDir;

    @JsonProperty("securityContext")
    private PodSecurityContext securityContext;

    @JsonProperty("takeSavepointOnUpdate")
    private Boolean takeSavepointOnUpdate;

    @JsonProperty("tolerations")
    private List<Toleration> tolerations = null;

    @JsonProperty("volumeMounts")
    private List<VolumeMount> volumeMounts = null;

    @JsonProperty("volumes")
    private List<Volume> volumes = null;


    public V1beta1FlinkClusterSpecJob allowNonRestoredState(Boolean allowNonRestoredState) {

        this.allowNonRestoredState = allowNonRestoredState;
        return this;
    }

    /**
     * Get allowNonRestoredState
     *
     * @return allowNonRestoredState
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getAllowNonRestoredState() {
        return allowNonRestoredState;
    }


    public void setAllowNonRestoredState(Boolean allowNonRestoredState) {
        this.allowNonRestoredState = allowNonRestoredState;
    }


    public V1beta1FlinkClusterSpecJob args(List<String> args) {

        this.args = args;
        return this;
    }

    public V1beta1FlinkClusterSpecJob addArgsItem(String argsItem) {
        if (this.args == null) {
            this.args = new ArrayList<>();
        }
        this.args.add(argsItem);
        return this;
    }

    /**
     * Get args
     *
     * @return args
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<String> getArgs() {
        return args;
    }


    public void setArgs(List<String> args) {
        this.args = args;
    }


    public V1beta1FlinkClusterSpecJob autoSavepointSeconds(Integer autoSavepointSeconds) {

        this.autoSavepointSeconds = autoSavepointSeconds;
        return this;
    }

    /**
     * Get autoSavepointSeconds
     *
     * @return autoSavepointSeconds
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getAutoSavepointSeconds() {
        return autoSavepointSeconds;
    }


    public void setAutoSavepointSeconds(Integer autoSavepointSeconds) {
        this.autoSavepointSeconds = autoSavepointSeconds;
    }


    public V1beta1FlinkClusterSpecJob cancelRequested(Boolean cancelRequested) {

        this.cancelRequested = cancelRequested;
        return this;
    }

    /**
     * Get cancelRequested
     *
     * @return cancelRequested
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getCancelRequested() {
        return cancelRequested;
    }


    public void setCancelRequested(Boolean cancelRequested) {
        this.cancelRequested = cancelRequested;
    }


    public V1beta1FlinkClusterSpecJob className(String className) {

        this.className = className;
        return this;
    }

    /**
     * Get className
     *
     * @return className
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getClassName() {
        return className;
    }


    public void setClassName(String className) {
        this.className = className;
    }


    public V1beta1FlinkClusterSpecJob cleanupPolicy(V1beta1FlinkClusterSpecJobCleanupPolicy cleanupPolicy) {

        this.cleanupPolicy = cleanupPolicy;
        return this;
    }

    /**
     * Get cleanupPolicy
     *
     * @return cleanupPolicy
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1beta1FlinkClusterSpecJobCleanupPolicy getCleanupPolicy() {
        return cleanupPolicy;
    }


    public void setCleanupPolicy(V1beta1FlinkClusterSpecJobCleanupPolicy cleanupPolicy) {
        this.cleanupPolicy = cleanupPolicy;
    }


    public V1beta1FlinkClusterSpecJob fromSavepoint(String fromSavepoint) {

        this.fromSavepoint = fromSavepoint;
        return this;
    }

    /**
     * Get fromSavepoint
     *
     * @return fromSavepoint
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getFromSavepoint() {
        return fromSavepoint;
    }


    public void setFromSavepoint(String fromSavepoint) {
        this.fromSavepoint = fromSavepoint;
    }


    public V1beta1FlinkClusterSpecJob initContainers(List<Container> initContainers) {

        this.initContainers = initContainers;
        return this;
    }

    public V1beta1FlinkClusterSpecJob addInitContainersItem(Container initContainersItem) {
        if (this.initContainers == null) {
            this.initContainers = new ArrayList<Container>();
        }
        this.initContainers.add(initContainersItem);
        return this;
    }

    /**
     * Get initContainers
     *
     * @return initContainers
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<Container> getInitContainers() {
        return initContainers;
    }


    public void setInitContainers(List<Container> initContainers) {
        this.initContainers = initContainers;
    }


    public V1beta1FlinkClusterSpecJob jarFile(String jarFile) {

        this.jarFile = jarFile;
        return this;
    }

    /**
     * Get jarFile
     *
     * @return jarFile
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getJarFile() {
        return jarFile;
    }


    public void setJarFile(String jarFile) {
        this.jarFile = jarFile;
    }


    public V1beta1FlinkClusterSpecJob maxStateAgeToRestoreSeconds(Integer maxStateAgeToRestoreSeconds) {

        this.maxStateAgeToRestoreSeconds = maxStateAgeToRestoreSeconds;
        return this;
    }

    /**
     * Get maxStateAgeToRestoreSeconds
     * minimum: 0
     *
     * @return maxStateAgeToRestoreSeconds
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getMaxStateAgeToRestoreSeconds() {
        return maxStateAgeToRestoreSeconds;
    }


    public void setMaxStateAgeToRestoreSeconds(Integer maxStateAgeToRestoreSeconds) {
        this.maxStateAgeToRestoreSeconds = maxStateAgeToRestoreSeconds;
    }


    public V1beta1FlinkClusterSpecJob mode(String mode) {

        this.mode = mode;
        return this;
    }

    /**
     * Get mode
     *
     * @return mode
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getMode() {
        return mode;
    }


    public void setMode(String mode) {
        this.mode = mode;
    }


    public V1beta1FlinkClusterSpecJob noLoggingToStdout(Boolean noLoggingToStdout) {

        this.noLoggingToStdout = noLoggingToStdout;
        return this;
    }

    /**
     * Get noLoggingToStdout
     *
     * @return noLoggingToStdout
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getNoLoggingToStdout() {
        return noLoggingToStdout;
    }


    public void setNoLoggingToStdout(Boolean noLoggingToStdout) {
        this.noLoggingToStdout = noLoggingToStdout;
    }


    public V1beta1FlinkClusterSpecJob nodeSelector(Map<String, String> nodeSelector) {

        this.nodeSelector = nodeSelector;
        return this;
    }

    public V1beta1FlinkClusterSpecJob putNodeSelectorItem(String key, String nodeSelectorItem) {
        if (this.nodeSelector == null) {
            this.nodeSelector = new HashMap<>();
        }
        this.nodeSelector.put(key, nodeSelectorItem);
        return this;
    }

    /**
     * Get nodeSelector
     *
     * @return nodeSelector
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Map<String, String> getNodeSelector() {
        return nodeSelector;
    }


    public void setNodeSelector(Map<String, String> nodeSelector) {
        this.nodeSelector = nodeSelector;
    }


    public V1beta1FlinkClusterSpecJob parallelism(Integer parallelism) {

        this.parallelism = parallelism;
        return this;
    }

    /**
     * Get parallelism
     *
     * @return parallelism
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getParallelism() {
        return parallelism;
    }


    public void setParallelism(Integer parallelism) {
        this.parallelism = parallelism;
    }


    public V1beta1FlinkClusterSpecJob podAnnotations(Map<String, String> podAnnotations) {

        this.podAnnotations = podAnnotations;
        return this;
    }

    public V1beta1FlinkClusterSpecJob putPodAnnotationsItem(String key, String podAnnotationsItem) {
        if (this.podAnnotations == null) {
            this.podAnnotations = new HashMap<>();
        }
        this.podAnnotations.put(key, podAnnotationsItem);
        return this;
    }

    /**
     * Get podAnnotations
     *
     * @return podAnnotations
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Map<String, String> getPodAnnotations() {
        return podAnnotations;
    }


    public void setPodAnnotations(Map<String, String> podAnnotations) {
        this.podAnnotations = podAnnotations;
    }


    public V1beta1FlinkClusterSpecJob podLabels(Map<String, String> podLabels) {

        this.podLabels = podLabels;
        return this;
    }

    public V1beta1FlinkClusterSpecJob putPodLabelsItem(String key, String podLabelsItem) {
        if (this.podLabels == null) {
            this.podLabels = new HashMap<>();
        }
        this.podLabels.put(key, podLabelsItem);
        return this;
    }

    /**
     * Get podLabels
     *
     * @return podLabels
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Map<String, String> getPodLabels() {
        return podLabels;
    }


    public void setPodLabels(Map<String, String> podLabels) {
        this.podLabels = podLabels;
    }


    public V1beta1FlinkClusterSpecJob pyFile(String pyFile) {

        this.pyFile = pyFile;
        return this;
    }

    /**
     * Get pyFile
     *
     * @return pyFile
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getPyFile() {
        return pyFile;
    }


    public void setPyFile(String pyFile) {
        this.pyFile = pyFile;
    }


    public V1beta1FlinkClusterSpecJob pyFiles(String pyFiles) {

        this.pyFiles = pyFiles;
        return this;
    }

    /**
     * Get pyFiles
     *
     * @return pyFiles
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getPyFiles() {
        return pyFiles;
    }


    public void setPyFiles(String pyFiles) {
        this.pyFiles = pyFiles;
    }


    public V1beta1FlinkClusterSpecJob pyModule(String pyModule) {

        this.pyModule = pyModule;
        return this;
    }

    /**
     * Get pyModule
     *
     * @return pyModule
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getPyModule() {
        return pyModule;
    }


    public void setPyModule(String pyModule) {
        this.pyModule = pyModule;
    }


    public V1beta1FlinkClusterSpecJob resources(ResourceRequirements resources) {

        this.resources = resources;
        return this;
    }

    /**
     * Get resources
     *
     * @return resources
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public ResourceRequirements getResources() {
        return resources;
    }


    public void setResources(ResourceRequirements resources) {
        this.resources = resources;
    }


    public V1beta1FlinkClusterSpecJob restartPolicy(String restartPolicy) {

        this.restartPolicy = restartPolicy;
        return this;
    }

    /**
     * Get restartPolicy
     *
     * @return restartPolicy
     **/
    @ApiModelProperty(required = true, value = "")

    public String getRestartPolicy() {
        return restartPolicy;
    }


    public void setRestartPolicy(String restartPolicy) {
        this.restartPolicy = restartPolicy;
    }


    public V1beta1FlinkClusterSpecJob savepointGeneration(Integer savepointGeneration) {

        this.savepointGeneration = savepointGeneration;
        return this;
    }

    /**
     * Get savepointGeneration
     *
     * @return savepointGeneration
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getSavepointGeneration() {
        return savepointGeneration;
    }


    public void setSavepointGeneration(Integer savepointGeneration) {
        this.savepointGeneration = savepointGeneration;
    }


    public V1beta1FlinkClusterSpecJob savepointsDir(String savepointsDir) {

        this.savepointsDir = savepointsDir;
        return this;
    }

    /**
     * Get savepointsDir
     *
     * @return savepointsDir
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getSavepointsDir() {
        return savepointsDir;
    }


    public void setSavepointsDir(String savepointsDir) {
        this.savepointsDir = savepointsDir;
    }


    public V1beta1FlinkClusterSpecJob securityContext(PodSecurityContext securityContext) {

        this.securityContext = securityContext;
        return this;
    }

    /**
     * Get securityContext
     *
     * @return securityContext
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public PodSecurityContext getSecurityContext() {
        return securityContext;
    }


    public void setSecurityContext(PodSecurityContext securityContext) {
        this.securityContext = securityContext;
    }


    public V1beta1FlinkClusterSpecJob takeSavepointOnUpdate(Boolean takeSavepointOnUpdate) {

        this.takeSavepointOnUpdate = takeSavepointOnUpdate;
        return this;
    }

    /**
     * Get takeSavepointOnUpdate
     *
     * @return takeSavepointOnUpdate
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getTakeSavepointOnUpdate() {
        return takeSavepointOnUpdate;
    }


    public void setTakeSavepointOnUpdate(Boolean takeSavepointOnUpdate) {
        this.takeSavepointOnUpdate = takeSavepointOnUpdate;
    }


    public V1beta1FlinkClusterSpecJob tolerations(List<Toleration> tolerations) {

        this.tolerations = tolerations;
        return this;
    }

    public V1beta1FlinkClusterSpecJob addTolerationsItem(Toleration tolerationsItem) {
        if (this.tolerations == null) {
            this.tolerations = new ArrayList<Toleration>();
        }
        this.tolerations.add(tolerationsItem);
        return this;
    }

    /**
     * Get tolerations
     *
     * @return tolerations
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<Toleration> getTolerations() {
        return tolerations;
    }


    public void setTolerations(List<Toleration> tolerations) {
        this.tolerations = tolerations;
    }


    public V1beta1FlinkClusterSpecJob volumeMounts(List<VolumeMount> volumeMounts) {

        this.volumeMounts = volumeMounts;
        return this;
    }

    public V1beta1FlinkClusterSpecJob addVolumeMountsItem(VolumeMount volumeMountsItem) {
        if (this.volumeMounts == null) {
            this.volumeMounts = new ArrayList<>();
        }
        this.volumeMounts.add(volumeMountsItem);
        return this;
    }

    /**
     * Get volumeMounts
     *
     * @return volumeMounts
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<VolumeMount> getVolumeMounts() {
        return volumeMounts;
    }


    public void setVolumeMounts(List<VolumeMount> volumeMounts) {
        this.volumeMounts = volumeMounts;
    }


    public V1beta1FlinkClusterSpecJob volumes(List<Volume> volumes) {

        this.volumes = volumes;
        return this;
    }

    public V1beta1FlinkClusterSpecJob addVolumesItem(Volume volumesItem) {
        if (this.volumes == null) {
            this.volumes = new ArrayList<>();
        }
        this.volumes.add(volumesItem);
        return this;
    }

    /**
     * Get volumes
     *
     * @return volumes
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<Volume> getVolumes() {
        return volumes;
    }


    public void setVolumes(List<Volume> volumes) {
        this.volumes = volumes;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta1FlinkClusterSpecJob v1beta1FlinkClusterSpecJob = (V1beta1FlinkClusterSpecJob) o;
        return Objects.equals(this.allowNonRestoredState, v1beta1FlinkClusterSpecJob.allowNonRestoredState) &&
                Objects.equals(this.args, v1beta1FlinkClusterSpecJob.args) &&
                Objects.equals(this.autoSavepointSeconds, v1beta1FlinkClusterSpecJob.autoSavepointSeconds) &&
                Objects.equals(this.cancelRequested, v1beta1FlinkClusterSpecJob.cancelRequested) &&
                Objects.equals(this.className, v1beta1FlinkClusterSpecJob.className) &&
                Objects.equals(this.cleanupPolicy, v1beta1FlinkClusterSpecJob.cleanupPolicy) &&
                Objects.equals(this.fromSavepoint, v1beta1FlinkClusterSpecJob.fromSavepoint) &&
                Objects.equals(this.initContainers, v1beta1FlinkClusterSpecJob.initContainers) &&
                Objects.equals(this.jarFile, v1beta1FlinkClusterSpecJob.jarFile) &&
                Objects.equals(this.maxStateAgeToRestoreSeconds,
                        v1beta1FlinkClusterSpecJob.maxStateAgeToRestoreSeconds) &&
                Objects.equals(this.mode, v1beta1FlinkClusterSpecJob.mode) &&
                Objects.equals(this.noLoggingToStdout, v1beta1FlinkClusterSpecJob.noLoggingToStdout) &&
                Objects.equals(this.nodeSelector, v1beta1FlinkClusterSpecJob.nodeSelector) &&
                Objects.equals(this.parallelism, v1beta1FlinkClusterSpecJob.parallelism) &&
                Objects.equals(this.podAnnotations, v1beta1FlinkClusterSpecJob.podAnnotations) &&
                Objects.equals(this.podLabels, v1beta1FlinkClusterSpecJob.podLabels) &&
                Objects.equals(this.pyFile, v1beta1FlinkClusterSpecJob.pyFile) &&
                Objects.equals(this.pyFiles, v1beta1FlinkClusterSpecJob.pyFiles) &&
                Objects.equals(this.pyModule, v1beta1FlinkClusterSpecJob.pyModule) &&
                Objects.equals(this.resources, v1beta1FlinkClusterSpecJob.resources) &&
                Objects.equals(this.restartPolicy, v1beta1FlinkClusterSpecJob.restartPolicy) &&
                Objects.equals(this.savepointGeneration, v1beta1FlinkClusterSpecJob.savepointGeneration) &&
                Objects.equals(this.savepointsDir, v1beta1FlinkClusterSpecJob.savepointsDir) &&
                Objects.equals(this.securityContext, v1beta1FlinkClusterSpecJob.securityContext) &&
                Objects.equals(this.takeSavepointOnUpdate, v1beta1FlinkClusterSpecJob.takeSavepointOnUpdate) &&
                Objects.equals(this.tolerations, v1beta1FlinkClusterSpecJob.tolerations) &&
                Objects.equals(this.volumeMounts, v1beta1FlinkClusterSpecJob.volumeMounts) &&
                Objects.equals(this.volumes, v1beta1FlinkClusterSpecJob.volumes);
    }

    @Override
    public int hashCode() {
        return Objects.hash(allowNonRestoredState, args, autoSavepointSeconds, cancelRequested, className,
                cleanupPolicy, fromSavepoint, initContainers, jarFile, maxStateAgeToRestoreSeconds, mode,
                noLoggingToStdout, nodeSelector, parallelism, podAnnotations, podLabels, pyFile, pyFiles, pyModule,
                resources, restartPolicy, savepointGeneration, savepointsDir, securityContext, takeSavepointOnUpdate,
                tolerations, volumeMounts, volumes);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta1FlinkClusterSpecJob {\n");
        sb.append("    allowNonRestoredState: ").append(toIndentedString(allowNonRestoredState)).append("\n");
        sb.append("    args: ").append(toIndentedString(args)).append("\n");
        sb.append("    autoSavepointSeconds: ").append(toIndentedString(autoSavepointSeconds)).append("\n");
        sb.append("    cancelRequested: ").append(toIndentedString(cancelRequested)).append("\n");
        sb.append("    className: ").append(toIndentedString(className)).append("\n");
        sb.append("    cleanupPolicy: ").append(toIndentedString(cleanupPolicy)).append("\n");
        sb.append("    fromSavepoint: ").append(toIndentedString(fromSavepoint)).append("\n");
        sb.append("    initContainers: ").append(toIndentedString(initContainers)).append("\n");
        sb.append("    jarFile: ").append(toIndentedString(jarFile)).append("\n");
        sb.append("    maxStateAgeToRestoreSeconds: ").append(toIndentedString(maxStateAgeToRestoreSeconds))
          .append("\n");
        sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
        sb.append("    noLoggingToStdout: ").append(toIndentedString(noLoggingToStdout)).append("\n");
        sb.append("    nodeSelector: ").append(toIndentedString(nodeSelector)).append("\n");
        sb.append("    parallelism: ").append(toIndentedString(parallelism)).append("\n");
        sb.append("    podAnnotations: ").append(toIndentedString(podAnnotations)).append("\n");
        sb.append("    podLabels: ").append(toIndentedString(podLabels)).append("\n");
        sb.append("    pyFile: ").append(toIndentedString(pyFile)).append("\n");
        sb.append("    pyFiles: ").append(toIndentedString(pyFiles)).append("\n");
        sb.append("    pyModule: ").append(toIndentedString(pyModule)).append("\n");
        sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
        sb.append("    restartPolicy: ").append(toIndentedString(restartPolicy)).append("\n");
        sb.append("    savepointGeneration: ").append(toIndentedString(savepointGeneration)).append("\n");
        sb.append("    savepointsDir: ").append(toIndentedString(savepointsDir)).append("\n");
        sb.append("    securityContext: ").append(toIndentedString(securityContext)).append("\n");
        sb.append("    takeSavepointOnUpdate: ").append(toIndentedString(takeSavepointOnUpdate)).append("\n");
        sb.append("    tolerations: ").append(toIndentedString(tolerations)).append("\n");
        sb.append("    volumeMounts: ").append(toIndentedString(volumeMounts)).append("\n");
        sb.append("    volumes: ").append(toIndentedString(volumes)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

