/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.k8s.flinkoperator;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta1FlinkClusterSpecJobCleanupPolicy
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-02-19T16:59" +
        ":54.980Z[Etc/UTC]")
public class V1beta1FlinkClusterSpecJobCleanupPolicy {
    @JsonProperty("afterJobCancelled")
    private String afterJobCancelled;

    @JsonProperty("afterJobFails")
    private String afterJobFails;

    @JsonProperty("afterJobSucceeds")
    private String afterJobSucceeds;


    public V1beta1FlinkClusterSpecJobCleanupPolicy afterJobCancelled(String afterJobCancelled) {

        this.afterJobCancelled = afterJobCancelled;
        return this;
    }

    /**
     * Get afterJobCancelled
     *
     * @return afterJobCancelled
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getAfterJobCancelled() {
        return afterJobCancelled;
    }


    public void setAfterJobCancelled(String afterJobCancelled) {
        this.afterJobCancelled = afterJobCancelled;
    }


    public V1beta1FlinkClusterSpecJobCleanupPolicy afterJobFails(String afterJobFails) {

        this.afterJobFails = afterJobFails;
        return this;
    }

    /**
     * Get afterJobFails
     *
     * @return afterJobFails
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getAfterJobFails() {
        return afterJobFails;
    }


    public void setAfterJobFails(String afterJobFails) {
        this.afterJobFails = afterJobFails;
    }


    public V1beta1FlinkClusterSpecJobCleanupPolicy afterJobSucceeds(String afterJobSucceeds) {

        this.afterJobSucceeds = afterJobSucceeds;
        return this;
    }

    /**
     * Get afterJobSucceeds
     *
     * @return afterJobSucceeds
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getAfterJobSucceeds() {
        return afterJobSucceeds;
    }


    public void setAfterJobSucceeds(String afterJobSucceeds) {
        this.afterJobSucceeds = afterJobSucceeds;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta1FlinkClusterSpecJobCleanupPolicy v1beta1FlinkClusterSpecJobCleanupPolicy =
                (V1beta1FlinkClusterSpecJobCleanupPolicy) o;
        return Objects.equals(this.afterJobCancelled, v1beta1FlinkClusterSpecJobCleanupPolicy.afterJobCancelled) &&
                Objects.equals(this.afterJobFails, v1beta1FlinkClusterSpecJobCleanupPolicy.afterJobFails) &&
                Objects.equals(this.afterJobSucceeds, v1beta1FlinkClusterSpecJobCleanupPolicy.afterJobSucceeds);
    }

    @Override
    public int hashCode() {
        return Objects.hash(afterJobCancelled, afterJobFails, afterJobSucceeds);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta1FlinkClusterSpecJobCleanupPolicy {\n");
        sb.append("    afterJobCancelled: ").append(toIndentedString(afterJobCancelled)).append("\n");
        sb.append("    afterJobFails: ").append(toIndentedString(afterJobFails)).append("\n");
        sb.append("    afterJobSucceeds: ").append(toIndentedString(afterJobSucceeds)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

