package io.k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecDriverEnvFrom
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecDriverEnvFrom {

    private V1beta2SparkApplicationSpecDriverConfigMapRef configMapRef;


    private String prefix;


    private V1beta2SparkApplicationSpecDriverConfigMapRef secretRef;


    public V1beta2SparkApplicationSpecDriverEnvFrom configMapRef(V1beta2SparkApplicationSpecDriverConfigMapRef configMapRef) {

        this.configMapRef = configMapRef;
        return this;
    }

    /**
     * Get configMapRef
     *
     * @return configMapRef
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1beta2SparkApplicationSpecDriverConfigMapRef getConfigMapRef() {
        return configMapRef;
    }


    public void setConfigMapRef(V1beta2SparkApplicationSpecDriverConfigMapRef configMapRef) {
        this.configMapRef = configMapRef;
    }


    public V1beta2SparkApplicationSpecDriverEnvFrom prefix(String prefix) {

        this.prefix = prefix;
        return this;
    }

    /**
     * Get prefix
     *
     * @return prefix
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getPrefix() {
        return prefix;
    }


    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }


    public V1beta2SparkApplicationSpecDriverEnvFrom secretRef(V1beta2SparkApplicationSpecDriverConfigMapRef secretRef) {

        this.secretRef = secretRef;
        return this;
    }

    /**
     * Get secretRef
     *
     * @return secretRef
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1beta2SparkApplicationSpecDriverConfigMapRef getSecretRef() {
        return secretRef;
    }


    public void setSecretRef(V1beta2SparkApplicationSpecDriverConfigMapRef secretRef) {
        this.secretRef = secretRef;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecDriverEnvFrom v1beta2SparkApplicationSpecDriverEnvFrom =
                (V1beta2SparkApplicationSpecDriverEnvFrom) o;
        return Objects.equals(this.configMapRef, v1beta2SparkApplicationSpecDriverEnvFrom.configMapRef) &&
                Objects.equals(this.prefix, v1beta2SparkApplicationSpecDriverEnvFrom.prefix) &&
                Objects.equals(this.secretRef, v1beta2SparkApplicationSpecDriverEnvFrom.secretRef);
    }

    @Override
    public int hashCode() {
        return Objects.hash(configMapRef, prefix, secretRef);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecDriverEnvFrom {\n");
        sb.append("    configMapRef: ").append(toIndentedString(configMapRef)).append("\n");
        sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
        sb.append("    secretRef: ").append(toIndentedString(secretRef)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

