package io.k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecFc
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecFc {

    private String fsType;


    private Integer lun;


    private Boolean readOnly;


    private List<String> targetWWNs = null;


    private List<String> wwids = null;


    public V1beta2SparkApplicationSpecFc fsType(String fsType) {

        this.fsType = fsType;
        return this;
    }

    /**
     * Get fsType
     *
     * @return fsType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getFsType() {
        return fsType;
    }


    public void setFsType(String fsType) {
        this.fsType = fsType;
    }


    public V1beta2SparkApplicationSpecFc lun(Integer lun) {

        this.lun = lun;
        return this;
    }

    /**
     * Get lun
     *
     * @return lun
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getLun() {
        return lun;
    }


    public void setLun(Integer lun) {
        this.lun = lun;
    }


    public V1beta2SparkApplicationSpecFc readOnly(Boolean readOnly) {

        this.readOnly = readOnly;
        return this;
    }

    /**
     * Get readOnly
     *
     * @return readOnly
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getReadOnly() {
        return readOnly;
    }


    public void setReadOnly(Boolean readOnly) {
        this.readOnly = readOnly;
    }


    public V1beta2SparkApplicationSpecFc targetWWNs(List<String> targetWWNs) {

        this.targetWWNs = targetWWNs;
        return this;
    }

    public V1beta2SparkApplicationSpecFc addTargetWWNsItem(String targetWWNsItem) {
        if (this.targetWWNs == null) {
            this.targetWWNs = new ArrayList<>();
        }
        this.targetWWNs.add(targetWWNsItem);
        return this;
    }

    /**
     * Get targetWWNs
     *
     * @return targetWWNs
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<String> getTargetWWNs() {
        return targetWWNs;
    }


    public void setTargetWWNs(List<String> targetWWNs) {
        this.targetWWNs = targetWWNs;
    }


    public V1beta2SparkApplicationSpecFc wwids(List<String> wwids) {

        this.wwids = wwids;
        return this;
    }

    public V1beta2SparkApplicationSpecFc addWwidsItem(String wwidsItem) {
        if (this.wwids == null) {
            this.wwids = new ArrayList<>();
        }
        this.wwids.add(wwidsItem);
        return this;
    }

    /**
     * Get wwids
     *
     * @return wwids
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<String> getWwids() {
        return wwids;
    }


    public void setWwids(List<String> wwids) {
        this.wwids = wwids;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecFc v1beta2SparkApplicationSpecFc = (V1beta2SparkApplicationSpecFc) o;
        return Objects.equals(this.fsType, v1beta2SparkApplicationSpecFc.fsType) &&
                Objects.equals(this.lun, v1beta2SparkApplicationSpecFc.lun) &&
                Objects.equals(this.readOnly, v1beta2SparkApplicationSpecFc.readOnly) &&
                Objects.equals(this.targetWWNs, v1beta2SparkApplicationSpecFc.targetWWNs) &&
                Objects.equals(this.wwids, v1beta2SparkApplicationSpecFc.wwids);
    }

    @Override
    public int hashCode() {
        return Objects.hash(fsType, lun, readOnly, targetWWNs, wwids);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecFc {\n");
        sb.append("    fsType: ").append(toIndentedString(fsType)).append("\n");
        sb.append("    lun: ").append(toIndentedString(lun)).append("\n");
        sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
        sb.append("    targetWWNs: ").append(toIndentedString(targetWWNs)).append("\n");
        sb.append("    wwids: ").append(toIndentedString(wwids)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

