package io.k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecDriverSecurityContextSeLinuxOptions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecDriverSecurityContextSeLinuxOptions {

    private String level;


    private String role;


    private String type;


    private String user;


    public V1beta2SparkApplicationSpecDriverSecurityContextSeLinuxOptions level(String level) {

        this.level = level;
        return this;
    }

    /**
     * Get level
     *
     * @return level
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getLevel() {
        return level;
    }


    public void setLevel(String level) {
        this.level = level;
    }


    public V1beta2SparkApplicationSpecDriverSecurityContextSeLinuxOptions role(String role) {

        this.role = role;
        return this;
    }

    /**
     * Get role
     *
     * @return role
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getRole() {
        return role;
    }


    public void setRole(String role) {
        this.role = role;
    }


    public V1beta2SparkApplicationSpecDriverSecurityContextSeLinuxOptions type(String type) {

        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getType() {
        return type;
    }


    public void setType(String type) {
        this.type = type;
    }


    public V1beta2SparkApplicationSpecDriverSecurityContextSeLinuxOptions user(String user) {

        this.user = user;
        return this;
    }

    /**
     * Get user
     *
     * @return user
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getUser() {
        return user;
    }


    public void setUser(String user) {
        this.user = user;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecDriverSecurityContextSeLinuxOptions v1beta2SparkApplicationSpecDriverSecurityContextSeLinuxOptions = (V1beta2SparkApplicationSpecDriverSecurityContextSeLinuxOptions) o;
        return Objects.equals(this.level, v1beta2SparkApplicationSpecDriverSecurityContextSeLinuxOptions.level) &&
                Objects.equals(this.role, v1beta2SparkApplicationSpecDriverSecurityContextSeLinuxOptions.role) &&
                Objects.equals(this.type, v1beta2SparkApplicationSpecDriverSecurityContextSeLinuxOptions.type) &&
                Objects.equals(this.user, v1beta2SparkApplicationSpecDriverSecurityContextSeLinuxOptions.user);
    }

    @Override
    public int hashCode() {
        return Objects.hash(level, role, type, user);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecDriverSecurityContextSeLinuxOptions {\n");
        sb.append("    level: ").append(toIndentedString(level)).append("\n");
        sb.append("    role: ").append(toIndentedString(role)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    user: ").append(toIndentedString(user)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

