package io.k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecFlocker
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecFlocker {

    private String datasetName;


    private String datasetUUID;


    public V1beta2SparkApplicationSpecFlocker datasetName(String datasetName) {

        this.datasetName = datasetName;
        return this;
    }

    /**
     * Get datasetName
     *
     * @return datasetName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getDatasetName() {
        return datasetName;
    }


    public void setDatasetName(String datasetName) {
        this.datasetName = datasetName;
    }


    public V1beta2SparkApplicationSpecFlocker datasetUUID(String datasetUUID) {

        this.datasetUUID = datasetUUID;
        return this;
    }

    /**
     * Get datasetUUID
     *
     * @return datasetUUID
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getDatasetUUID() {
        return datasetUUID;
    }


    public void setDatasetUUID(String datasetUUID) {
        this.datasetUUID = datasetUUID;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecFlocker v1beta2SparkApplicationSpecFlocker = (V1beta2SparkApplicationSpecFlocker) o;
        return Objects.equals(this.datasetName, v1beta2SparkApplicationSpecFlocker.datasetName) &&
                Objects.equals(this.datasetUUID, v1beta2SparkApplicationSpecFlocker.datasetUUID);
    }

    @Override
    public int hashCode() {
        return Objects.hash(datasetName, datasetUUID);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecFlocker {\n");
        sb.append("    datasetName: ").append(toIndentedString(datasetName)).append("\n");
        sb.append("    datasetUUID: ").append(toIndentedString(datasetUUID)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

