package io.k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecDriverLifecyclePostStartTcpSocket
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecDriverLifecyclePostStartTcpSocket {

    private String host;


    private Object port;


    public V1beta2SparkApplicationSpecDriverLifecyclePostStartTcpSocket host(String host) {

        this.host = host;
        return this;
    }

    /**
     * Get host
     *
     * @return host
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getHost() {
        return host;
    }


    public void setHost(String host) {
        this.host = host;
    }


    public V1beta2SparkApplicationSpecDriverLifecyclePostStartTcpSocket port(Object port) {

        this.port = port;
        return this;
    }

    /**
     * Get port
     *
     * @return port
     **/
    @ApiModelProperty(required = true, value = "")

    public Object getPort() {
        return port;
    }


    public void setPort(Object port) {
        this.port = port;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecDriverLifecyclePostStartTcpSocket v1beta2SparkApplicationSpecDriverLifecyclePostStartTcpSocket = (V1beta2SparkApplicationSpecDriverLifecyclePostStartTcpSocket) o;
        return Objects.equals(this.host, v1beta2SparkApplicationSpecDriverLifecyclePostStartTcpSocket.host) &&
                Objects.equals(this.port, v1beta2SparkApplicationSpecDriverLifecyclePostStartTcpSocket.port);
    }

    @Override
    public int hashCode() {
        return Objects.hash(host, port);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecDriverLifecyclePostStartTcpSocket {\n");
        sb.append("    host: ").append(toIndentedString(host)).append("\n");
        sb.append("    port: ").append(toIndentedString(port)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

