package io.k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecEmptyDir
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecEmptyDir {

    private String medium;


    private Object sizeLimit;


    public V1beta2SparkApplicationSpecEmptyDir medium(String medium) {

        this.medium = medium;
        return this;
    }

    /**
     * Get medium
     *
     * @return medium
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getMedium() {
        return medium;
    }


    public void setMedium(String medium) {
        this.medium = medium;
    }


    public V1beta2SparkApplicationSpecEmptyDir sizeLimit(Object sizeLimit) {

        this.sizeLimit = sizeLimit;
        return this;
    }

    /**
     * Get sizeLimit
     *
     * @return sizeLimit
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Object getSizeLimit() {
        return sizeLimit;
    }


    public void setSizeLimit(Object sizeLimit) {
        this.sizeLimit = sizeLimit;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecEmptyDir v1beta2SparkApplicationSpecEmptyDir =
                (V1beta2SparkApplicationSpecEmptyDir) o;
        return Objects.equals(this.medium, v1beta2SparkApplicationSpecEmptyDir.medium) &&
                Objects.equals(this.sizeLimit, v1beta2SparkApplicationSpecEmptyDir.sizeLimit);
    }

    @Override
    public int hashCode() {
        return Objects.hash(medium, sizeLimit);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecEmptyDir {\n");
        sb.append("    medium: ").append(toIndentedString(medium)).append("\n");
        sb.append("    sizeLimit: ").append(toIndentedString(sizeLimit)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

