package io.k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecDriverLifecycle
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecDriverLifecycle {

    private V1beta2SparkApplicationSpecDriverLifecyclePostStart postStart;


    private V1beta2SparkApplicationSpecDriverLifecyclePostStart preStop;


    public V1beta2SparkApplicationSpecDriverLifecycle postStart(V1beta2SparkApplicationSpecDriverLifecyclePostStart postStart) {

        this.postStart = postStart;
        return this;
    }

    /**
     * Get postStart
     *
     * @return postStart
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1beta2SparkApplicationSpecDriverLifecyclePostStart getPostStart() {
        return postStart;
    }


    public void setPostStart(V1beta2SparkApplicationSpecDriverLifecyclePostStart postStart) {
        this.postStart = postStart;
    }


    public V1beta2SparkApplicationSpecDriverLifecycle preStop(V1beta2SparkApplicationSpecDriverLifecyclePostStart preStop) {

        this.preStop = preStop;
        return this;
    }

    /**
     * Get preStop
     *
     * @return preStop
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1beta2SparkApplicationSpecDriverLifecyclePostStart getPreStop() {
        return preStop;
    }


    public void setPreStop(V1beta2SparkApplicationSpecDriverLifecyclePostStart preStop) {
        this.preStop = preStop;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecDriverLifecycle v1beta2SparkApplicationSpecDriverLifecycle =
                (V1beta2SparkApplicationSpecDriverLifecycle) o;
        return Objects.equals(this.postStart, v1beta2SparkApplicationSpecDriverLifecycle.postStart) &&
                Objects.equals(this.preStop, v1beta2SparkApplicationSpecDriverLifecycle.preStop);
    }

    @Override
    public int hashCode() {
        return Objects.hash(postStart, preStop);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecDriverLifecycle {\n");
        sb.append("    postStart: ").append(toIndentedString(postStart)).append("\n");
        sb.append("    preStop: ").append(toIndentedString(preStop)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

