package io.k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecScaleIO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecScaleIO {

    private String fsType;


    private String gateway;


    private String protectionDomain;


    private Boolean readOnly;


    private V1beta2SparkApplicationSpecCephfsSecretRef secretRef;


    private Boolean sslEnabled;


    private String storageMode;


    private String storagePool;


    private String system;


    private String volumeName;


    public V1beta2SparkApplicationSpecScaleIO fsType(String fsType) {

        this.fsType = fsType;
        return this;
    }

    /**
     * Get fsType
     *
     * @return fsType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getFsType() {
        return fsType;
    }


    public void setFsType(String fsType) {
        this.fsType = fsType;
    }


    public V1beta2SparkApplicationSpecScaleIO gateway(String gateway) {

        this.gateway = gateway;
        return this;
    }

    /**
     * Get gateway
     *
     * @return gateway
     **/
    @ApiModelProperty(required = true, value = "")

    public String getGateway() {
        return gateway;
    }


    public void setGateway(String gateway) {
        this.gateway = gateway;
    }


    public V1beta2SparkApplicationSpecScaleIO protectionDomain(String protectionDomain) {

        this.protectionDomain = protectionDomain;
        return this;
    }

    /**
     * Get protectionDomain
     *
     * @return protectionDomain
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getProtectionDomain() {
        return protectionDomain;
    }


    public void setProtectionDomain(String protectionDomain) {
        this.protectionDomain = protectionDomain;
    }


    public V1beta2SparkApplicationSpecScaleIO readOnly(Boolean readOnly) {

        this.readOnly = readOnly;
        return this;
    }

    /**
     * Get readOnly
     *
     * @return readOnly
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getReadOnly() {
        return readOnly;
    }


    public void setReadOnly(Boolean readOnly) {
        this.readOnly = readOnly;
    }


    public V1beta2SparkApplicationSpecScaleIO secretRef(V1beta2SparkApplicationSpecCephfsSecretRef secretRef) {

        this.secretRef = secretRef;
        return this;
    }

    /**
     * Get secretRef
     *
     * @return secretRef
     **/
    @ApiModelProperty(required = true, value = "")

    public V1beta2SparkApplicationSpecCephfsSecretRef getSecretRef() {
        return secretRef;
    }


    public void setSecretRef(V1beta2SparkApplicationSpecCephfsSecretRef secretRef) {
        this.secretRef = secretRef;
    }


    public V1beta2SparkApplicationSpecScaleIO sslEnabled(Boolean sslEnabled) {

        this.sslEnabled = sslEnabled;
        return this;
    }

    /**
     * Get sslEnabled
     *
     * @return sslEnabled
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getSslEnabled() {
        return sslEnabled;
    }


    public void setSslEnabled(Boolean sslEnabled) {
        this.sslEnabled = sslEnabled;
    }


    public V1beta2SparkApplicationSpecScaleIO storageMode(String storageMode) {

        this.storageMode = storageMode;
        return this;
    }

    /**
     * Get storageMode
     *
     * @return storageMode
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getStorageMode() {
        return storageMode;
    }


    public void setStorageMode(String storageMode) {
        this.storageMode = storageMode;
    }


    public V1beta2SparkApplicationSpecScaleIO storagePool(String storagePool) {

        this.storagePool = storagePool;
        return this;
    }

    /**
     * Get storagePool
     *
     * @return storagePool
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getStoragePool() {
        return storagePool;
    }


    public void setStoragePool(String storagePool) {
        this.storagePool = storagePool;
    }


    public V1beta2SparkApplicationSpecScaleIO system(String system) {

        this.system = system;
        return this;
    }

    /**
     * Get system
     *
     * @return system
     **/
    @ApiModelProperty(required = true, value = "")

    public String getSystem() {
        return system;
    }


    public void setSystem(String system) {
        this.system = system;
    }


    public V1beta2SparkApplicationSpecScaleIO volumeName(String volumeName) {

        this.volumeName = volumeName;
        return this;
    }

    /**
     * Get volumeName
     *
     * @return volumeName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getVolumeName() {
        return volumeName;
    }


    public void setVolumeName(String volumeName) {
        this.volumeName = volumeName;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecScaleIO v1beta2SparkApplicationSpecScaleIO = (V1beta2SparkApplicationSpecScaleIO) o;
        return Objects.equals(this.fsType, v1beta2SparkApplicationSpecScaleIO.fsType) &&
                Objects.equals(this.gateway, v1beta2SparkApplicationSpecScaleIO.gateway) &&
                Objects.equals(this.protectionDomain, v1beta2SparkApplicationSpecScaleIO.protectionDomain) &&
                Objects.equals(this.readOnly, v1beta2SparkApplicationSpecScaleIO.readOnly) &&
                Objects.equals(this.secretRef, v1beta2SparkApplicationSpecScaleIO.secretRef) &&
                Objects.equals(this.sslEnabled, v1beta2SparkApplicationSpecScaleIO.sslEnabled) &&
                Objects.equals(this.storageMode, v1beta2SparkApplicationSpecScaleIO.storageMode) &&
                Objects.equals(this.storagePool, v1beta2SparkApplicationSpecScaleIO.storagePool) &&
                Objects.equals(this.system, v1beta2SparkApplicationSpecScaleIO.system) &&
                Objects.equals(this.volumeName, v1beta2SparkApplicationSpecScaleIO.volumeName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(fsType, gateway, protectionDomain, readOnly, secretRef, sslEnabled, storageMode,
                storagePool, system, volumeName);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecScaleIO {\n");
        sb.append("    fsType: ").append(toIndentedString(fsType)).append("\n");
        sb.append("    gateway: ").append(toIndentedString(gateway)).append("\n");
        sb.append("    protectionDomain: ").append(toIndentedString(protectionDomain)).append("\n");
        sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
        sb.append("    secretRef: ").append(toIndentedString(secretRef)).append("\n");
        sb.append("    sslEnabled: ").append(toIndentedString(sslEnabled)).append("\n");
        sb.append("    storageMode: ").append(toIndentedString(storageMode)).append("\n");
        sb.append("    storagePool: ").append(toIndentedString(storagePool)).append("\n");
        sb.append("    system: ").append(toIndentedString(system)).append("\n");
        sb.append("    volumeName: ").append(toIndentedString(volumeName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

