package io.k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecDriverConfigMapRef
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecDriverConfigMapRef {

    private String name;


    private Boolean optional;


    public V1beta2SparkApplicationSpecDriverConfigMapRef name(String name) {

        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getName() {
        return name;
    }


    public void setName(String name) {
        this.name = name;
    }


    public V1beta2SparkApplicationSpecDriverConfigMapRef optional(Boolean optional) {

        this.optional = optional;
        return this;
    }

    /**
     * Get optional
     *
     * @return optional
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getOptional() {
        return optional;
    }


    public void setOptional(Boolean optional) {
        this.optional = optional;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecDriverConfigMapRef v1beta2SparkApplicationSpecDriverConfigMapRef =
                (V1beta2SparkApplicationSpecDriverConfigMapRef) o;
        return Objects.equals(this.name, v1beta2SparkApplicationSpecDriverConfigMapRef.name) &&
                Objects.equals(this.optional, v1beta2SparkApplicationSpecDriverConfigMapRef.optional);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, optional);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecDriverConfigMapRef {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    optional: ").append(toIndentedString(optional)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

