package io.k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferenceMatchExpressions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferenceMatchExpressions {

    private String key;


    private String operator;


    private List<String> values = null;


    public V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferenceMatchExpressions key(String key) {

        this.key = key;
        return this;
    }

    /**
     * Get key
     *
     * @return key
     **/
    @ApiModelProperty(required = true, value = "")

    public String getKey() {
        return key;
    }


    public void setKey(String key) {
        this.key = key;
    }


    public V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferenceMatchExpressions operator(String operator) {

        this.operator = operator;
        return this;
    }

    /**
     * Get operator
     *
     * @return operator
     **/
    @ApiModelProperty(required = true, value = "")

    public String getOperator() {
        return operator;
    }


    public void setOperator(String operator) {
        this.operator = operator;
    }


    public V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferenceMatchExpressions values(List<String> values) {

        this.values = values;
        return this;
    }

    public V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferenceMatchExpressions addValuesItem(String valuesItem) {
        if (this.values == null) {
            this.values = new ArrayList<>();
        }
        this.values.add(valuesItem);
        return this;
    }

    /**
     * Get values
     *
     * @return values
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<String> getValues() {
        return values;
    }


    public void setValues(List<String> values) {
        this.values = values;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferenceMatchExpressions v1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferenceMatchExpressions = (V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferenceMatchExpressions) o;
        return Objects.equals(this.key,
                v1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferenceMatchExpressions.key) &&
                Objects.equals(this.operator,
                        v1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferenceMatchExpressions.operator) &&
                Objects.equals(this.values,
                        v1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferenceMatchExpressions.values);
    }

    @Override
    public int hashCode() {
        return Objects.hash(key, operator, values);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecDriverAffinityNodeAffinityPreferenceMatchExpressions {\n");
        sb.append("    key: ").append(toIndentedString(key)).append("\n");
        sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
        sb.append("    values: ").append(toIndentedString(values)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

