package io.k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecDriverAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecution
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecDriverAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecution {

    private V1beta2SparkApplicationSpecDriverAffinityPodAffinityPodAffinityTerm podAffinityTerm;


    private Integer weight;


    public V1beta2SparkApplicationSpecDriverAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecution podAffinityTerm(V1beta2SparkApplicationSpecDriverAffinityPodAffinityPodAffinityTerm podAffinityTerm) {

        this.podAffinityTerm = podAffinityTerm;
        return this;
    }

    /**
     * Get podAffinityTerm
     *
     * @return podAffinityTerm
     **/
    @ApiModelProperty(required = true, value = "")

    public V1beta2SparkApplicationSpecDriverAffinityPodAffinityPodAffinityTerm getPodAffinityTerm() {
        return podAffinityTerm;
    }


    public void setPodAffinityTerm(V1beta2SparkApplicationSpecDriverAffinityPodAffinityPodAffinityTerm podAffinityTerm) {
        this.podAffinityTerm = podAffinityTerm;
    }


    public V1beta2SparkApplicationSpecDriverAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecution weight(Integer weight) {

        this.weight = weight;
        return this;
    }

    /**
     * Get weight
     *
     * @return weight
     **/
    @ApiModelProperty(required = true, value = "")

    public Integer getWeight() {
        return weight;
    }


    public void setWeight(Integer weight) {
        this.weight = weight;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecDriverAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecution v1beta2SparkApplicationSpecDriverAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecution = (V1beta2SparkApplicationSpecDriverAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecution) o;
        return Objects.equals(this.podAffinityTerm,
                v1beta2SparkApplicationSpecDriverAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecution.podAffinityTerm) &&
                Objects.equals(this.weight,
                        v1beta2SparkApplicationSpecDriverAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecution.weight);
    }

    @Override
    public int hashCode() {
        return Objects.hash(podAffinityTerm, weight);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class " +
                "V1beta2SparkApplicationSpecDriverAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecution " +
                "{\n");
        sb.append("    podAffinityTerm: ").append(toIndentedString(podAffinityTerm)).append("\n");
        sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

