package io.k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecGcePersistentDisk
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecGcePersistentDisk {

    private String fsType;


    private Integer partition;


    private String pdName;


    private Boolean readOnly;


    public V1beta2SparkApplicationSpecGcePersistentDisk fsType(String fsType) {

        this.fsType = fsType;
        return this;
    }

    /**
     * Get fsType
     *
     * @return fsType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getFsType() {
        return fsType;
    }


    public void setFsType(String fsType) {
        this.fsType = fsType;
    }


    public V1beta2SparkApplicationSpecGcePersistentDisk partition(Integer partition) {

        this.partition = partition;
        return this;
    }

    /**
     * Get partition
     *
     * @return partition
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getPartition() {
        return partition;
    }


    public void setPartition(Integer partition) {
        this.partition = partition;
    }


    public V1beta2SparkApplicationSpecGcePersistentDisk pdName(String pdName) {

        this.pdName = pdName;
        return this;
    }

    /**
     * Get pdName
     *
     * @return pdName
     **/
    @ApiModelProperty(required = true, value = "")

    public String getPdName() {
        return pdName;
    }


    public void setPdName(String pdName) {
        this.pdName = pdName;
    }


    public V1beta2SparkApplicationSpecGcePersistentDisk readOnly(Boolean readOnly) {

        this.readOnly = readOnly;
        return this;
    }

    /**
     * Get readOnly
     *
     * @return readOnly
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getReadOnly() {
        return readOnly;
    }


    public void setReadOnly(Boolean readOnly) {
        this.readOnly = readOnly;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecGcePersistentDisk v1beta2SparkApplicationSpecGcePersistentDisk =
                (V1beta2SparkApplicationSpecGcePersistentDisk) o;
        return Objects.equals(this.fsType, v1beta2SparkApplicationSpecGcePersistentDisk.fsType) &&
                Objects.equals(this.partition, v1beta2SparkApplicationSpecGcePersistentDisk.partition) &&
                Objects.equals(this.pdName, v1beta2SparkApplicationSpecGcePersistentDisk.pdName) &&
                Objects.equals(this.readOnly, v1beta2SparkApplicationSpecGcePersistentDisk.readOnly);
    }

    @Override
    public int hashCode() {
        return Objects.hash(fsType, partition, pdName, readOnly);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecGcePersistentDisk {\n");
        sb.append("    fsType: ").append(toIndentedString(fsType)).append("\n");
        sb.append("    partition: ").append(toIndentedString(partition)).append("\n");
        sb.append("    pdName: ").append(toIndentedString(pdName)).append("\n");
        sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

