package io.k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecDriverResources
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecDriverResources {

    private Map<String, Object> limits = null;


    private Map<String, Object> requests = null;


    public V1beta2SparkApplicationSpecDriverResources limits(Map<String, Object> limits) {

        this.limits = limits;
        return this;
    }

    public V1beta2SparkApplicationSpecDriverResources putLimitsItem(String key, Object limitsItem) {
        if (this.limits == null) {
            this.limits = new HashMap<>();
        }
        this.limits.put(key, limitsItem);
        return this;
    }

    /**
     * Get limits
     *
     * @return limits
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Map<String, Object> getLimits() {
        return limits;
    }


    public void setLimits(Map<String, Object> limits) {
        this.limits = limits;
    }


    public V1beta2SparkApplicationSpecDriverResources requests(Map<String, Object> requests) {

        this.requests = requests;
        return this;
    }

    public V1beta2SparkApplicationSpecDriverResources putRequestsItem(String key, Object requestsItem) {
        if (this.requests == null) {
            this.requests = new HashMap<>();
        }
        this.requests.put(key, requestsItem);
        return this;
    }

    /**
     * Get requests
     *
     * @return requests
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Map<String, Object> getRequests() {
        return requests;
    }


    public void setRequests(Map<String, Object> requests) {
        this.requests = requests;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecDriverResources v1beta2SparkApplicationSpecDriverResources =
                (V1beta2SparkApplicationSpecDriverResources) o;
        return Objects.equals(this.limits, v1beta2SparkApplicationSpecDriverResources.limits) &&
                Objects.equals(this.requests, v1beta2SparkApplicationSpecDriverResources.requests);
    }

    @Override
    public int hashCode() {
        return Objects.hash(limits, requests);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecDriverResources {\n");
        sb.append("    limits: ").append(toIndentedString(limits)).append("\n");
        sb.append("    requests: ").append(toIndentedString(requests)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

