package io.k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecIscsi
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecIscsi {

    private Boolean chapAuthDiscovery;


    private Boolean chapAuthSession;


    private String fsType;


    private String initiatorName;


    private String iqn;


    private String iscsiInterface;


    private Integer lun;


    private List<String> portals = null;


    private Boolean readOnly;


    private V1beta2SparkApplicationSpecCephfsSecretRef secretRef;


    private String targetPortal;


    public V1beta2SparkApplicationSpecIscsi chapAuthDiscovery(Boolean chapAuthDiscovery) {

        this.chapAuthDiscovery = chapAuthDiscovery;
        return this;
    }

    /**
     * Get chapAuthDiscovery
     *
     * @return chapAuthDiscovery
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getChapAuthDiscovery() {
        return chapAuthDiscovery;
    }


    public void setChapAuthDiscovery(Boolean chapAuthDiscovery) {
        this.chapAuthDiscovery = chapAuthDiscovery;
    }


    public V1beta2SparkApplicationSpecIscsi chapAuthSession(Boolean chapAuthSession) {

        this.chapAuthSession = chapAuthSession;
        return this;
    }

    /**
     * Get chapAuthSession
     *
     * @return chapAuthSession
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getChapAuthSession() {
        return chapAuthSession;
    }


    public void setChapAuthSession(Boolean chapAuthSession) {
        this.chapAuthSession = chapAuthSession;
    }


    public V1beta2SparkApplicationSpecIscsi fsType(String fsType) {

        this.fsType = fsType;
        return this;
    }

    /**
     * Get fsType
     *
     * @return fsType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getFsType() {
        return fsType;
    }


    public void setFsType(String fsType) {
        this.fsType = fsType;
    }


    public V1beta2SparkApplicationSpecIscsi initiatorName(String initiatorName) {

        this.initiatorName = initiatorName;
        return this;
    }

    /**
     * Get initiatorName
     *
     * @return initiatorName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getInitiatorName() {
        return initiatorName;
    }


    public void setInitiatorName(String initiatorName) {
        this.initiatorName = initiatorName;
    }


    public V1beta2SparkApplicationSpecIscsi iqn(String iqn) {

        this.iqn = iqn;
        return this;
    }

    /**
     * Get iqn
     *
     * @return iqn
     **/
    @ApiModelProperty(required = true, value = "")

    public String getIqn() {
        return iqn;
    }


    public void setIqn(String iqn) {
        this.iqn = iqn;
    }


    public V1beta2SparkApplicationSpecIscsi iscsiInterface(String iscsiInterface) {

        this.iscsiInterface = iscsiInterface;
        return this;
    }

    /**
     * Get iscsiInterface
     *
     * @return iscsiInterface
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getIscsiInterface() {
        return iscsiInterface;
    }


    public void setIscsiInterface(String iscsiInterface) {
        this.iscsiInterface = iscsiInterface;
    }


    public V1beta2SparkApplicationSpecIscsi lun(Integer lun) {

        this.lun = lun;
        return this;
    }

    /**
     * Get lun
     *
     * @return lun
     **/
    @ApiModelProperty(required = true, value = "")

    public Integer getLun() {
        return lun;
    }


    public void setLun(Integer lun) {
        this.lun = lun;
    }


    public V1beta2SparkApplicationSpecIscsi portals(List<String> portals) {

        this.portals = portals;
        return this;
    }

    public V1beta2SparkApplicationSpecIscsi addPortalsItem(String portalsItem) {
        if (this.portals == null) {
            this.portals = new ArrayList<>();
        }
        this.portals.add(portalsItem);
        return this;
    }

    /**
     * Get portals
     *
     * @return portals
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<String> getPortals() {
        return portals;
    }


    public void setPortals(List<String> portals) {
        this.portals = portals;
    }


    public V1beta2SparkApplicationSpecIscsi readOnly(Boolean readOnly) {

        this.readOnly = readOnly;
        return this;
    }

    /**
     * Get readOnly
     *
     * @return readOnly
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getReadOnly() {
        return readOnly;
    }


    public void setReadOnly(Boolean readOnly) {
        this.readOnly = readOnly;
    }


    public V1beta2SparkApplicationSpecIscsi secretRef(V1beta2SparkApplicationSpecCephfsSecretRef secretRef) {

        this.secretRef = secretRef;
        return this;
    }

    /**
     * Get secretRef
     *
     * @return secretRef
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1beta2SparkApplicationSpecCephfsSecretRef getSecretRef() {
        return secretRef;
    }


    public void setSecretRef(V1beta2SparkApplicationSpecCephfsSecretRef secretRef) {
        this.secretRef = secretRef;
    }


    public V1beta2SparkApplicationSpecIscsi targetPortal(String targetPortal) {

        this.targetPortal = targetPortal;
        return this;
    }

    /**
     * Get targetPortal
     *
     * @return targetPortal
     **/
    @ApiModelProperty(required = true, value = "")

    public String getTargetPortal() {
        return targetPortal;
    }


    public void setTargetPortal(String targetPortal) {
        this.targetPortal = targetPortal;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecIscsi v1beta2SparkApplicationSpecIscsi = (V1beta2SparkApplicationSpecIscsi) o;
        return Objects.equals(this.chapAuthDiscovery, v1beta2SparkApplicationSpecIscsi.chapAuthDiscovery) &&
                Objects.equals(this.chapAuthSession, v1beta2SparkApplicationSpecIscsi.chapAuthSession) &&
                Objects.equals(this.fsType, v1beta2SparkApplicationSpecIscsi.fsType) &&
                Objects.equals(this.initiatorName, v1beta2SparkApplicationSpecIscsi.initiatorName) &&
                Objects.equals(this.iqn, v1beta2SparkApplicationSpecIscsi.iqn) &&
                Objects.equals(this.iscsiInterface, v1beta2SparkApplicationSpecIscsi.iscsiInterface) &&
                Objects.equals(this.lun, v1beta2SparkApplicationSpecIscsi.lun) &&
                Objects.equals(this.portals, v1beta2SparkApplicationSpecIscsi.portals) &&
                Objects.equals(this.readOnly, v1beta2SparkApplicationSpecIscsi.readOnly) &&
                Objects.equals(this.secretRef, v1beta2SparkApplicationSpecIscsi.secretRef) &&
                Objects.equals(this.targetPortal, v1beta2SparkApplicationSpecIscsi.targetPortal);
    }

    @Override
    public int hashCode() {
        return Objects.hash(chapAuthDiscovery, chapAuthSession, fsType, initiatorName, iqn, iscsiInterface, lun,
                portals, readOnly, secretRef, targetPortal);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecIscsi {\n");
        sb.append("    chapAuthDiscovery: ").append(toIndentedString(chapAuthDiscovery)).append("\n");
        sb.append("    chapAuthSession: ").append(toIndentedString(chapAuthSession)).append("\n");
        sb.append("    fsType: ").append(toIndentedString(fsType)).append("\n");
        sb.append("    initiatorName: ").append(toIndentedString(initiatorName)).append("\n");
        sb.append("    iqn: ").append(toIndentedString(iqn)).append("\n");
        sb.append("    iscsiInterface: ").append(toIndentedString(iscsiInterface)).append("\n");
        sb.append("    lun: ").append(toIndentedString(lun)).append("\n");
        sb.append("    portals: ").append(toIndentedString(portals)).append("\n");
        sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
        sb.append("    secretRef: ").append(toIndentedString(secretRef)).append("\n");
        sb.append("    targetPortal: ").append(toIndentedString(targetPortal)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

