package io.k8s.sparkoperator;/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecFlexVolume
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-30T13:32" +
        ":37.998Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecFlexVolume {

    private String driver;


    private String fsType;


    private Map<String, String> options = null;


    private Boolean readOnly;


    private V1beta2SparkApplicationSpecCephfsSecretRef secretRef;


    public V1beta2SparkApplicationSpecFlexVolume driver(String driver) {

        this.driver = driver;
        return this;
    }

    /**
     * Get driver
     *
     * @return driver
     **/
    @ApiModelProperty(required = true, value = "")

    public String getDriver() {
        return driver;
    }


    public void setDriver(String driver) {
        this.driver = driver;
    }


    public V1beta2SparkApplicationSpecFlexVolume fsType(String fsType) {

        this.fsType = fsType;
        return this;
    }

    /**
     * Get fsType
     *
     * @return fsType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getFsType() {
        return fsType;
    }


    public void setFsType(String fsType) {
        this.fsType = fsType;
    }


    public V1beta2SparkApplicationSpecFlexVolume options(Map<String, String> options) {

        this.options = options;
        return this;
    }

    public V1beta2SparkApplicationSpecFlexVolume putOptionsItem(String key, String optionsItem) {
        if (this.options == null) {
            this.options = new HashMap<>();
        }
        this.options.put(key, optionsItem);
        return this;
    }

    /**
     * Get options
     *
     * @return options
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Map<String, String> getOptions() {
        return options;
    }


    public void setOptions(Map<String, String> options) {
        this.options = options;
    }


    public V1beta2SparkApplicationSpecFlexVolume readOnly(Boolean readOnly) {

        this.readOnly = readOnly;
        return this;
    }

    /**
     * Get readOnly
     *
     * @return readOnly
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getReadOnly() {
        return readOnly;
    }


    public void setReadOnly(Boolean readOnly) {
        this.readOnly = readOnly;
    }


    public V1beta2SparkApplicationSpecFlexVolume secretRef(V1beta2SparkApplicationSpecCephfsSecretRef secretRef) {

        this.secretRef = secretRef;
        return this;
    }

    /**
     * Get secretRef
     *
     * @return secretRef
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1beta2SparkApplicationSpecCephfsSecretRef getSecretRef() {
        return secretRef;
    }


    public void setSecretRef(V1beta2SparkApplicationSpecCephfsSecretRef secretRef) {
        this.secretRef = secretRef;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecFlexVolume v1beta2SparkApplicationSpecFlexVolume =
                (V1beta2SparkApplicationSpecFlexVolume) o;
        return Objects.equals(this.driver, v1beta2SparkApplicationSpecFlexVolume.driver) &&
                Objects.equals(this.fsType, v1beta2SparkApplicationSpecFlexVolume.fsType) &&
                Objects.equals(this.options, v1beta2SparkApplicationSpecFlexVolume.options) &&
                Objects.equals(this.readOnly, v1beta2SparkApplicationSpecFlexVolume.readOnly) &&
                Objects.equals(this.secretRef, v1beta2SparkApplicationSpecFlexVolume.secretRef);
    }

    @Override
    public int hashCode() {
        return Objects.hash(driver, fsType, options, readOnly, secretRef);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecFlexVolume {\n");
        sb.append("    driver: ").append(toIndentedString(driver)).append("\n");
        sb.append("    fsType: ").append(toIndentedString(fsType)).append("\n");
        sb.append("    options: ").append(toIndentedString(options)).append("\n");
        sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
        sb.append("    secretRef: ").append(toIndentedString(secretRef)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

