package de.tuberlin.batchjoboperator.web.extender;

import com.fasterxml.jackson.annotation.JsonProperty;
import de.tuberlin.batchjoboperator.reconciler.slots.ApplicationPodView;
import io.fabric8.kubernetes.api.model.Pod;
import lombok.RequiredArgsConstructor;
import lombok.Value;

import java.util.Map;

@Value
@RequiredArgsConstructor
public class ExtenderPreemptionArgs {
    // Pod being scheduled
    @JsonProperty("Pod")
    Pod pod;
    // Victims map generated by scheduler preemption phase
    // Only set NodeNameToMetaVictims if Extender.NodeCacheCapable == true. Otherwise, only set NodeNameToVictims.
    @JsonProperty("NodeNameToVictims")
    Map<String, Victims> nodeNameToVictims;

    @JsonProperty("NodeNameToMetaVictims")
    Map<String, MetaVictims> nodeNameToMetaVictims;

    public String toString() {
        return "ExtenderPreemptionArgs(pod=" + ApplicationPodView.wrap(pod) + ", " +
                "nodeNameToVictims=" + this.getNodeNameToVictims() + ", nodeNameToMetaVictims=" + this.getNodeNameToMetaVictims() + ")";
    }
}
